function finish with value:
    replacement:
        @intrinsic("return", value)

section if condition:
    replacement:
        @intrinsic("if", condition)

function the negative of value:
    execute:
        finish with @intrinsic("negate", value)

function the first result at depth:
    execute:
        if @intrinsic("greater than", depth, 0):
            finish with the negative of (the second result at @intrinsic("subtract", depth, 1))
        finish with 7.0

function the second result at depth:
    execute:
        if @intrinsic("greater than", depth, 0):
            finish with the negative of (the first result at @intrinsic("subtract", depth, 1))
        finish with 7.0

if @intrinsic("not equal", the first result at 3, @intrinsic("negate", 7.0)):
    @intrinsic("return", 1)
if @intrinsic("not equal", the second result at 4, 7.0):
    @intrinsic("return", 2)
@intrinsic("return", 0)
