function boolean:
    replacement:
        @intrinsic("type", "bool")

function return value:
    replacement:
        @intrinsic("return", value)

function consume support {boolean:support}:
    execute:
        return support

function control support {boolean:value}:
    execute:
        return value

function [before support {boolean:support}|after {boolean:support} support]:
    execute:
        return support

function shared [before support|after support] {boolean:support}:
    execute:
        return support

function label label {word:label}:
    execute:
        return label

function:
    patterns:
        select value {boolean:value}
        select {boolean:value} value
        select implicit value
    execute:
        return value

class:
    patterns:
        holder
    members:
        instance as boolean

@intrinsic("discard", consume support @intrinsic("equal", 1, 1))
@intrinsic("discard", control support @intrinsic("equal", 1, 1))
@intrinsic("discard", before support @intrinsic("equal", 1, 1))
@intrinsic("discard", after @intrinsic("equal", 1, 1) support)
@intrinsic("discard", shared before support @intrinsic("equal", 1, 1))
@intrinsic("discard", shared after support @intrinsic("equal", 1, 1))
@intrinsic("discard", label label token)
@intrinsic("discard", select value @intrinsic("equal", 1, 1))
@intrinsic("discard", select @intrinsic("equal", 1, 1) value)
@intrinsic("discard", select implicit @intrinsic("equal", 1, 1))
@intrinsic("store", holder_value, @intrinsic("construct", holder, @intrinsic("equal", 1, 1)))
@intrinsic("discard", the instance of holder_value)
