function [an|] integer:
    replacement:
        @intrinsic("type", "int")

function [a|] floating-point number:
    replacement:
        @intrinsic("type", "float")

function ignore value:
    replacement:
        @intrinsic("discard", value)

implicitly convert {integer:value}:
    replacement:
        2.0

function the required floating value from {a floating-point number:value}:
    replacement:
        value

ignore (the required floating value from 1)
