import lib/std.dl

flex function the nested branch condition for value:
    replacement:
        @intrinsic("if", value)

flex function the twice nested branch condition for value:
    replacement:
        the nested branch condition for value

flex section when truth satisfies the nested branch condition:
    replacement:
        the twice nested branch condition for truth

flex function the nested loop condition for value:
    replacement:
        @intrinsic("loop while", value)

flex section while truth satisfies the nested loop condition:
    replacement:
        the nested loop condition for truth

function publish a branch for condition:
    execute:
        when condition satisfies the nested branch condition:
            set the subject to 1
        else:
            set the subject to 2
        ignore it

function publish a loop for condition:
    execute:
        while condition satisfies the nested loop condition:
            set the subject to 3
        ignore it

publish a branch for true
publish a loop for false
