function return value:
	replacement:
		@intrinsic("return", value)

function set variable to value:
    replacement:
        @intrinsic("store", variable, value)

function ignore value:
    replacement:
        @intrinsic("discard", value)

function fixed quantity:
    replacement:
        @intrinsic("fix", quantity)

function [an|] integer:
    replacement:
        @intrinsic("type", "int")

function [a|] {fixed integer:bits} bit integer:
    replacement:
        @intrinsic("type", "int", bits)

function value as [a|] {fixed integer:bits} bit integer:
    replacement:
        @intrinsic("cast", value, @intrinsic("type", "int", bits))

function affirmative if condition, else negative:
    replacement:
        @intrinsic("select", condition, affirmative, negative)

function the build target is WebAssembly:
    replacement:
        @intrinsic("target is", "wasm")

function left = right:
    replacement:
        @intrinsic("equal", left, right)

function the WebAssembly output result for message:
    replacement:
        @intrinsic("call", "env", "dynlex_print_i64", a 32 bit integer, message as a 64 bit integer)

function the native output result for message:
    replacement:
        @intrinsic("variadic call", "libc", "printf", a 32 bit integer, 1, "%ld", message as a 64 bit integer)

function print message:
    replacement:
        ignore (
            (the WebAssembly output result for message)
            if the build target is WebAssembly,
            else (the native output result for message)
        )

function left + right:
    replacement:
        @intrinsic("add", left, right)

# Simple test
set first to 42
set second to 10
#this matches 'set $ to $' and the second '$' matches '$ + $'
set total to first  + second
print total
