macro expression return value:
	replacement:
		@intrinsic("return", value)

macro expression set var to val:
    replacement:
        @intrinsic("store", var, val)

macro expression value as [a|an|] bits bit integer:
    replacement:
        @intrinsic("cast", value, @intrinsic("type", "int", bits))

expression print msg:
    execute:
        @intrinsic("call", "libc", "printf", "i32", "%ld", msg as a 64 bit integer)

macro expression left + right:
    replacement:
        @intrinsic("add", left, right)

# Simple test
set x to 42
set y to 10
#this matches 'set $ to $' and the second '$' matches '$ + $'
set z to x  + y
print z