function return value:
	replacement:
		@intrinsic("return", value)

function set var to val:
    replacement:
        @intrinsic("store", var, val)

function discard val:
    replacement:
        @intrinsic("discard", val)

function [an|a|] {fixed integer:bits} bit integer:
    replacement:
        @intrinsic("type", "int", bits)

function value as [a|an|] {fixed integer:bits} bit integer:
    replacement:
        @intrinsic("cast", value, @intrinsic("type", "int", bits))

function true_value if condition, else false_value:
    replacement:
        @intrinsic("select", condition, true_value, false_value)

function [the|] build target is {word:platform}:
    replacement:
        @intrinsic("target is", platform)

function left = right:
    replacement:
        @intrinsic("equal", left, right)

function wasm print msg:
    replacement:
        @intrinsic("call", "env", "dynlex_print_i64", a 32 bit integer, msg as a 64 bit integer)

function native print msg:
    replacement:
        @intrinsic("call", "libc", "printf", a 32 bit integer, "%ld", msg as a 64 bit integer)

function print msg:
    execute:
        discard (wasm print msg) if the build target is wasm, else (native print msg)

function left + right:
    replacement:
        @intrinsic("add", left, right)

# Simple test
set x to 42
set y to 10
#this matches 'set $ to $' and the second '$' matches '$ + $'
set z to x  + y
print z
