function finish with value:
    replacement:
        @intrinsic("return", value)

section if condition:
    replacement:
        @intrinsic("if", condition)

function the negative of value:
    execute:
        finish with @intrinsic("negate", value)

function the alternating result at depth:
    execute:
        if @intrinsic("greater than", depth, 0):
            finish with the negative of (the alternating result at @intrinsic("subtract", depth, 1))
        finish with 7.0

if @intrinsic("not equal", the alternating result at 3, @intrinsic("negate", 7.0)):
    @intrinsic("return", 1)
if @intrinsic("not equal", the alternating result at 4, 7.0):
    @intrinsic("return", 2)
@intrinsic("return", 0)
