import lib/std.dl

class:
    patterns:
        point
    members:
        x
        y

function new point with x px and y py:
    execute:
        set result to @intrinsic("construct", point)
        set the x of result to px
        set the y of result to py
        return result

set p to new point with x 10 and y 20
print the x of p as line
print p's y as line
print the x of p + the y of p as line

# Type cast tests
print 3.14 as an integer as line
print 42 as a 16 bit integer as line
print 7 as a byte as line
print 100 as a float as line
