macro effect set var to val:
    replacement:
        @intrinsic("store", var, val)

macro expression value as [a|an|] bits bit integer:
    replacement:
        @intrinsic("cast", value, "integer", bits)

effect print msg as line:
    execute:
        @intrinsic("call", "libc", "printf", "i32", "%ld\n", msg as a 64 bit integer)

macro expression left + right:
    replacement:
        @intrinsic("add", left, right)

class:
    patterns:
        point
    members:
        x
        y

macro expression new point with x px and y py:
    replacement:
        @intrinsic("construct", point, px, py)

macro expression:
    patterns:
        the {word:propertyname} of ownername
        ownername's {word:propertyname}
    replacement:
        @intrinsic("property", ownername, propertyname)

set p to new point with x 10 and y 20
print the x of p as line
print p's y as line
print the x of p + the y of p as line
