import json.dl

parse "01" as JSON and set leading to it
print whether leading succeeded as a line
print the JSON error position in leading as a line
free leading

parse "1." as JSON and set fraction to it
print whether fraction succeeded as a line
print the JSON error position in fraction as a line
free fraction

parse "1e+" as JSON and set exponent to it
print whether exponent succeeded as a line
print the JSON error position in exponent as a line
free exponent

parse "\"\\x\"" as JSON and set escape to it
print whether escape succeeded as a line
print the JSON error position in escape as a line
free escape

parse "\"\\ud800\"" as JSON and set surrogate to it
print whether surrogate succeeded as a line
print the JSON error position in surrogate as a line
free surrogate

parse "[1,]" as JSON and set trailing to it
print whether trailing succeeded as a line
print the JSON error position in trailing as a line
free trailing
