import lib/std.dl

function the loose opposite of value:
    after: $ + $
    execute:
        return -value

function the tight opposite of value:
    before: $ + $
    execute:
        return -value

function value loosely inverted:
    after: $ + $
    execute:
        return -value

function value tightly inverted:
    before: $ + $
    execute:
        return -value

print (the loose opposite of 2 + 1) as a line
print (the tight opposite of 2 + 1) as a line
print (1 + 2 loosely inverted) as a line
print (1 + 2 tightly inverted) as a line
