function [a|] pointer to pointee:
    replacement:
        @intrinsic("add pointer depth", pointee)

function [a|] boolean:
    replacement:
        @intrinsic("type", "bool")

function value as destination:
    replacement:
        @intrinsic("cast", value, destination)

function ignore value:
    replacement:
        @intrinsic("discard", value)

flex section if condition:
    replacement:
        @intrinsic("if", condition)

class:
    patterns:
        [a|] sample
    members:
        number

function the requested pointer for {boolean:condition}:
    execute:
        if condition:
            @intrinsic("return", 0 as a pointer to a sample)
        @intrinsic("store", instance, @intrinsic("construct", a sample, 1))
        @intrinsic("return", @intrinsic("address of", instance))

ignore the requested pointer for @intrinsic("equal", 0, 0)
