function [a|] pointer to pointee:
    replacement:
        @intrinsic("add pointer depth", pointee)

function [a|] thirty two bit integer:
    replacement:
        @intrinsic("type", "int", 32)

function value as destination:
    replacement:
        @intrinsic("cast", value, destination)

function set variable to value:
    replacement:
        @intrinsic("store", variable, value)

function ignore value:
    replacement:
        @intrinsic("discard", value)

class:
    patterns:
        [a|] recursive value
    members:
        children as a pointer to a pointer to a recursive value
        length as a thirty two bit integer

set empty to 0 as a pointer to a pointer to a recursive value
set initial to @intrinsic("construct", a recursive value, empty, 0)
ignore the children of initial
