import lib/filesystem.dl

set path to "tests/required/filesystem_copy_same/content.tmp"
delete the filesystem entry at path

set stream to @intrinsic("call", "libc", "fopen", a pointer to a byte, path, "wb")
ignore @intrinsic("call", "libc", "fputs", an integer, "payload", stream)
ignore @intrinsic("call", "libc", "fclose", an integer, stream)

copy the filesystem entry at path to path
print whether it succeeded as a line

allocate 8 bytes and set contents to it
set stream to @intrinsic("call", "libc", "fopen", a pointer to a byte, path, "rb")
ignore @intrinsic("call", "libc", "fgets", a pointer to a byte, contents, 8, stream)
ignore @intrinsic("call", "libc", "fclose", an integer, stream)
ignore @intrinsic("variadic call", "libc", "printf", an integer, 1, "%s\n", contents)
@intrinsic("call", "libc", "free", nothing, contents)

delete the filesystem entry at path
