function ignore value:
    replacement:
        @intrinsic("discard", value)

function [an|] integer:
    replacement:
        @intrinsic("type", "int")

class:
    patterns:
        [a|] box
    members:
        value as an integer

@intrinsic("store", value, @intrinsic("construct", a box, 1))
@intrinsic("store", pointer, @intrinsic("address of", value))
@intrinsic("store", indirect, @intrinsic("address of", pointer))
ignore @intrinsic("address of", @intrinsic("property", indirect, "value"))
