function ignore value:
    replacement:
        @intrinsic("discard", value)

function [an|] integer:
    replacement:
        @intrinsic("type", "int")

class:
    patterns:
        [a|] box
    members:
        value as an integer

@intrinsic("store", value, @intrinsic("construct", a box, 1))
@intrinsic("store", pointer, @intrinsic("address of", value))
@intrinsic("store", indirect, @intrinsic("address of", pointer))
@intrinsic("store", field, @intrinsic("address of", @intrinsic("property", indirect, "value")))
@intrinsic("store at", field, 42)
ignore @intrinsic("variadic call", "libc", "printf", an integer, 1, "%d\n", @intrinsic("property", value, "value"))
