function [a|] byte:
    replacement:
        @intrinsic("type", "int", 8)

function [a|] pointer to pointed_type:
    replacement:
        @intrinsic("add pointer depth", pointed_type)

function value as destination_type:
    execute:
        return @intrinsic("cast", value, destination_type)

function discard value:
    replacement:
        @intrinsic("discard", value)

function return value:
    replacement:
        @intrinsic("return", value)

function an empty pointer:
    execute:
        return 0 as a pointer to byte

discard an empty pointer
