function [a|] byte:
    replacement:
        @intrinsic("type", "int", 8)

function [a|] pointer to pointee:
    replacement:
        @intrinsic("add pointer depth", pointee)

function value as destination:
    execute:
        return @intrinsic("cast", value, destination)

function ignore value:
    replacement:
        @intrinsic("discard", value)

function return value:
    replacement:
        @intrinsic("return", value)

function an empty pointer:
    execute:
        return 0 as a pointer to a byte

ignore an empty pointer
