import lib/std.dl

effect main:
    execute:
        set msg to "Hello"

        # Test string length
        set len to the length of msg
        print integer len on a new line

        # Test character access
        set char0 to character 0 of msg
        set char1 to character 1 of msg
        set char2 to character 2 of msg
        set char3 to character 3 of msg
        set char4 to character 4 of msg

        print integer char0 on a new line
        print integer char1 on a new line
        print integer char2 on a new line
        print integer char3 on a new line
        print integer char4 on a new line
