import lib/font.dl
import lib/graphics.dl

set window to a new window with width 400 and height 400
set font to a loaded font from "games/fonts/LiberationMono-Regular.ttf" at size 24

loop while not the window should close:
	clear screen

	# Just text, no rectangles
	draw text "HELLO WORLD" at 50 50 using font and color 255 255 255

	display the frame of window
	sleep for 100 milliseconds

close the window
