import lib/graphics.dl
import lib/font.dl

set window to a new window with width 128 and height 64
if window = 0 as a pointer to a byte:
    return 1

set {font loading} to the result of loading a font from "tests/games/fonts/LiberationMono-Regular.ttf" at size 32 for window
set typeface to font loading's typeface
if font loading failed:
    set {font release} to the result of releasing (the address of typeface)
    close the window
    return 1
if typeface's texture is loaded = false:
    set {font release} to the result of releasing (the address of typeface)
    close the window
    return 1

set frame to a new graphics frame in window
use screen coordinates in frame
set rendering to the result of drawing "A A" as text at x 16 and y 48 using typeface in color red 255, green 255 and blue 255 in frame
display frame

set {font release} to the result of releasing (the address of typeface)
set cleared to ((typeface's library = 0 as a pointer to a byte) and (typeface's face = 0 as a pointer to a byte)) and (typeface's texture is loaded = false)
close the window
if rendering failed or (font release failed or (cleared = false)):
    return 1
return 0
