import lib/graphics.dl

set hidden to a new hidden window with width 128 and height 64
if hidden = 0 as a pointer to a byte:
	return 1

set visible to @intrinsic("call", "glfw", "glfwGetWindowAttrib", an integer, hidden, the GLFW visible window hint)
set failed to visible != 0
@intrinsic("call", "glfw", "glfwDestroyWindow", nothing, hidden)

set window to a new window with width 128 and height 64
if window = 0 as a pointer to a byte:
	return 1

set visible_after_hidden to @intrinsic("call", "glfw", "glfwGetWindowAttrib", an integer, window, the GLFW visible window hint)
if visible_after_hidden != 1:
	set failed to true
@intrinsic("call", "glfw", "glfwDestroyWindow", nothing, window)
@intrinsic("call", "glfw", "glfwTerminate", nothing)

if failed:
	return 1
return 0
