import lib/graphics.dl

set window to a new window with width 128 and height 64
if window = 0 as a pointer to a byte:
	return 1

set failed to false
if key (the W key) is down in window:
	set failed to true
if key (the A key) is down in window:
	set failed to true
if key (the up arrow key) is down in window:
	set failed to true
if key (the left arrow key) is down in window:
	set failed to true
if key (the 1 key) is down in window:
	set failed to true
if key (the escape key) is down in window:
	set failed to true

if key (the W key) is up in window = false:
	set failed to true
if key (the 1 key) is up in window = false:
	set failed to true

close the window
if failed:
	return 1
