import lib/graphics.dl

set window to a new window with width 128 and height 64
if window = 0 as a pointer to a byte:
	return 1

set frame to a new graphics frame in window
display frame

set position to the cursor position of window
ignore position's x
ignore position's y
ignore the left mouse button is pressed in window
ignore the left mouse button is released in window

capture the mouse cursor in window
release the mouse cursor in window

request that window close
if window should close = false:
	close window
	return 1

close window
return 0
