import lib/std.dl

class:
    patterns:
        [a|] padded data
    members:
        first as a pointer to a byte
        count as a 32 bit integer
        second as a pointer to a byte
        total as a 32 bit integer

set zero to 0
set one to 1
set beginning to zero as a pointer to a byte
set ending to one as a pointer to a byte
set value to @intrinsic("construct", a padded data, beginning, 11, ending, 22)

print the count of value as a line
print the total of value as a line
