macro expression set var to val:
	replacement:
		@intrinsic("store", var, val)

macro expression [an|a|] integer:
	replacement:
		@intrinsic("type", "int", 32)

expression say msg:
	execute:
		@intrinsic("call", "libc", "printf", an integer, "%s\n", msg)

macro expression value as [a|an|] bits bit integer:
	replacement:
		@intrinsic("cast", value, @intrinsic("type", "int", bits))

expression print msg:
	execute:
		@intrinsic("call", "libc", "printf", an integer, "%ld\n", msg as a 64 bit integer)

expression customadder:
	execute:
		say "custom adder:"
		set result to @intrinsic("add", 1, 2)
		print result

customadder