function [a|] byte:
    replacement:
        @intrinsic("type", "int", 8)

function [a|] thirty two bit integer:
    replacement:
        @intrinsic("type", "int", 32)

function [a|] pointer to pointee:
    replacement:
        @intrinsic("add pointer depth", pointee)

function the size of measured:
    replacement:
        @intrinsic("size of", measured)

function ignore value:
    replacement:
        @intrinsic("discard", value)

class:
    patterns:
        [a|] padded value
    members:
        data as a pointer to a byte
        length as a thirty two bit integer

ignore @intrinsic("call", "libc", "printf", a thirty two bit integer, "%lld\n", the size of a padded value)
