function set variable to value:
    replacement:
        @intrinsic("store", variable, value)

function [an|] integer:
    replacement:
        @intrinsic("type", "int")

set values to [7]
@intrinsic(
    "discard",
    @intrinsic(
        "call",
        "libc",
        "printf",
        an integer,
        "%d\n",
        @intrinsic("dereference", @intrinsic("cast", @intrinsic("address of", values), @intrinsic("add pointer depth", @intrinsic("type", "int"))))
    )
)
