import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { createFarm, createWorker, addItem, capacity, relocate, moveFlag, distance } from "../../web/farm-world.js";
import { createRoles } from "../../web/farm-roles.js";
import { perform, sense } from "../../web/farm-actions.js";
import { parseFarmPlan, newRoutine, advanceRoutine } from "../../web/farm-program.js";
import { updateEnvironment, tickFarm, deliverOrder, assignRole } from "../../web/farm-simulation.js";
import { ACTIONS, DESTINATIONS, ITEMS, action, condition, itemId, targetId } from "../../web/farm-vocabulary.js";

const arg = key => ITEMS.find(item => item.key === key).id;
const dest = key => DESTINATIONS.find(item => item.key === key).id;
const world = createFarm(), worker = world.workers[0];
assert.deepEqual(createRoles().map(role => role.id), ["lumberjack"]);
assert.equal(world.workers.length, 1);
assert.equal(world.cow, null);
assert.equal(world.chickens.length, 2);
assert.equal(sense(world, worker, condition("hungry",{target:targetId("cow")})), false);
assert.match(perform(world, worker, action("feed",{target:targetId("cow")})).message, /no longer there/i);
assert.match(perform(world, worker, action("collect",{argument:itemId("milk")})).message, /No selected items/i);
assert.equal(world.tiles.flat().length, 400);
assert.equal(addItem(worker, "axe"), 1);
assert.equal(addItem(worker, "logs", 8), 3);
assert.equal(capacity(worker, "seeds"), 0);
assert.equal(worker.inventory.length, 2);
Object.assign(worker, { x: 3, y: 12 });
perform(world, worker, action("store"));
assert.equal(world.stock.logs, 3);
assert.equal(worker.inventory.length, 0);
perform(world, worker, action("collect",{argument:arg("axe")}));
Object.assign(worker, { x: 1, y: 9, direction: 0 });
assert.equal(sense(world, worker, condition("exists",{target:targetId("sightedTree")})), true);
assert.equal(perform(world, worker, action("chop")).done, false);
perform(world, worker, action("chop"));
perform(world, worker, action("chop"));
assert.equal(world.tiles[8][1].tree.regrow, 180);
perform(world, worker, action("collect"));
assert.equal(worker.inventory.find(i => i.kind === "logs").count, 2);
const receiver = createWorker("worker-2", "Bo", 1, 10); world.workers.push(receiver);
Object.assign(receiver, { x: 1, y: 10 });
perform(world, worker, action("give",{argument:arg("logs")}));
assert.equal(receiver.inventory[0].count, 2);
assert.equal(worker.inventory.length, 1);
receiver.inventory = []; worker.inventory = [];
addItem(worker, "bucket"); worker.inventory[0].water = 4;
perform(world, worker, action("give",{argument:arg("bucket")}));
assert.equal(receiver.inventory[0].water, 4, "Passing a bucket also passes its water");
perform(world, receiver, action("drop"));
assert.equal(receiver.inventory.length, 0);
addItem(receiver, "bucket");
perform(world, receiver, action("collect"));
assert.equal(receiver.inventory.length, 2, "Two hands can carry two of the same tool");
assert.equal(sense(world, receiver, condition("empty",{argument:itemId("bucket"),amount:1})), false, "The second bucket can still provide water");
assert.equal(relocate(world, worker.id, 6, 9), true);
assert.equal(relocate(world, worker.id, 3, 4), false, "A worker cannot be dropped in the pond");
assert.equal(relocate(world, "player", 6, 10), false, "Dragging is for workers");
assert.equal(relocate(world, worker.id, receiver.x, receiver.y), false);
assert.equal(moveFlag(world, "red", 9, 13), true);
for (let i = 0; i < 40 && distance(worker, world.flags[0]) > 1; i++) perform(world, worker, action("walk",{target:dest("red")}));
assert.ok(distance(worker, world.flags[0]) <= 1);

const farm = createFarm(), farmer = farm.player;
Object.assign(farmer, { x: 8, y: 12, direction: 0 });
addItem(farmer, "hoe"); addItem(farmer, "seeds", 3);
perform(farm, farmer, action("plow")); perform(farm, farmer, action("plant"));
assert.equal(farm.tiles[11][8].crop.growth, 0);
farmer.inventory = []; addItem(farmer, "bucket");
Object.assign(farmer, { x: 6, y: 4, direction: 3 });
perform(farm, farmer, action("fill"));
Object.assign(farmer, { x: 8, y: 12, direction: 0 });
perform(farm, farmer, action("water"));
assert.equal(farm.tiles[11][8].moisture, 10);
for (let i = 0; i < 40; i++) { farm.tick++; updateEnvironment(farm); }
assert.equal(farm.tiles[11][8].crop.growth, 1);
farmer.inventory = [];
perform(farm, farmer, action("harvest"));
assert.deepEqual(farmer.inventory.map(i => i.kind), ["carrots", "scraps"]);
assert.equal(farm.tiles[11][8].crop, null);

const irrigation = createFarm();
updateEnvironment(irrigation);
assert.equal(irrigation.tiles[7][7].water, false);
Object.assign(irrigation.player, { x: 6, y: 6, direction: 0 });
addItem(irrigation.player, "shovel"); perform(irrigation, irrigation.player, action("dig"));
updateEnvironment(irrigation);
assert.equal(irrigation.tiles[7][7].water, true, "Opening the pond connection fills the connected channels");
irrigation.tick = 75; updateEnvironment(irrigation);
assert.equal(irrigation.raining, true);
assert.equal(irrigation.tiles[9][8].moisture, 10);

const animals = createFarm(), keeper = animals.player;
animals.stock.carrots = 4; animals.stock.logs = 2;
assert.equal(deliverOrder(animals), true);
assert.equal(animals.workers.length, 2);
assert.equal(animals.workers[1].name, "Bo");
assert.equal(animals.cow, null, "The first order unlocks a worker, not the cow");
assert.equal(animals.stock.carrots, 0);
animals.stock.wheat = 4; animals.stock.eggs = 2;
assert.equal(deliverOrder(animals), true);
assert.equal(animals.expanded, true);
assert.deepEqual(animals.cow, { id: "cow", ...animals.pasture, direction: 2, feed: 0, progress: 0, produce: 0 });
addItem(keeper, "hay"); Object.assign(keeper, { x: 13, y: 4 });
perform(animals, keeper, action("feed",{target:targetId("cow")}));
addItem(keeper, "wheat"); Object.assign(keeper, { x: 12, y: 8 });
perform(animals, keeper, action("feed",{target:targetId("chickens")}));
for (let i = 0; i < 20; i++) updateEnvironment(animals);
perform(animals, keeper, action("collect",{argument:itemId("eggs")}));
for (let i=0;i<40;i++) if (perform(animals, keeper, action("walk",{target:dest("cow")})).done) break;
perform(animals, keeper, action("collect",{argument:itemId("milk")}));
assert.deepEqual(keeper.inventory.map(i => i.kind), ["eggs", "milk"]);
keeper.inventory = []; addItem(keeper, "scraps", 2); Object.assign(keeper, { x: 4, y: 8 });
perform(animals, keeper, action("add"));
for (let i = 0; i < 20; i++) updateEnvironment(animals);
perform(animals, keeper, action("collect",{argument:itemId("fertilizer"),target:targetId("compost")}));
assert.equal(keeper.inventory[0].kind, "fertilizer");
Object.assign(keeper, { x: 8, y: 8, direction: 2 });
perform(animals, keeper, action("fertilize"));
assert.equal(animals.tiles[9][8].fertilizer, 1);
const normal = animals.tiles[10][9], fertilized = animals.tiles[9][8];
normal.crop.growth = fertilized.crop.growth = 0;
updateEnvironment(animals);
assert.equal(fertilized.crop.growth, normal.crop.growth * 2);

const plan = parseFarmPlan(readFileSync(new URL("../required/farm_challenge/expected.txt", import.meta.url), "utf8"));
const routine = newRoutine();
const calls = [];
for (let i = 0; i < 8; i++) advanceRoutine(routine, plan, () => true, ({key}) => { calls.push(key); return { done: true, message: key }; });
assert.deepEqual(calls, ["chop", "wait", "wait", "chop", "wait", "wait", "chop", "wait"]);
assert.throws(() => parseFarmPlan("ELSE\nEND"));
const waitId = ACTIONS.find(a => a.key === "wait").id;
const zero = parseFarmPlan(`LOOP|0\nDO|${waitId}|0|-1|-2|\nEND\nDO|${waitId}|0|-1|-2|`);
const zeroState = newRoutine(); let waits = 0;
advanceRoutine(zeroState, zero, () => true, () => { waits++; return { done: true, message: "wait" }; });
advanceRoutine(zeroState, zero, () => true, () => { waits++; return { done: true, message: "wait" }; });
assert.equal(waits, 1, "A zero-count loop skips its body");
const forever = parseFarmPlan(`LOOP|-1\nIF|4|0|-1|-2|\nDO|${waitId}|0|-1|-2|\nEND\nEND`);
assert.match(advanceRoutine(newRoutine(), forever, () => false, () => assert.fail()), /condition/);
const rainRole = { id: "waterer", program: forever };
assignRole(animals.workers[0], rainRole.id);
tickFarm(animals, [rainRole]);
assert.equal(animals.workers[0].routine.finished, false);
console.log("Farm plans, inventory, tools, farming, irrigation, weather, animals, compost, handoffs, dragging and rewards passed.");
