import { installEditorAccess } from "./editor_test_driver.mjs";
import assert from "node:assert/strict";
import { captureScreenshot, clickElement, closeBrowserSession, command, evaluate, navigate, runtimeExceptions, waitFor } from "./browser_test_driver.mjs";

await navigate("/");
await installEditorAccess();
await waitFor("document.querySelector('[data-live-shader-banner]').dataset.shaderPlaylistReady === 'true'", "homepage compiler initialization");
await clickElement("[data-farm-challenge-load]");
await waitFor("document.querySelector('[data-farm-board]')?.dataset.rendered === 'true'", "3D farm rendering");
await waitFor("document.querySelector('[data-river-challenge-mount]').dataset.challengeLoaded === 'farm'", "farm semantic highlighting");
assert.deepEqual(await evaluate("Array.from(document.querySelector('[data-farm-role]').options, option=>option.text)"), ["Lumberjack"]);
assert.equal(await evaluate("document.querySelectorAll('[data-farm-worker]').length"), 2, "Start with the farmer and one worker");
const depth = await evaluate(`(() => { const gl=document.querySelector('[data-farm-board] canvas').getContext('webgl2'); return { depth:gl.getParameter(gl.DEPTH_BITS), enabled:gl.isEnabled(gl.DEPTH_TEST) }; })()`);
assert.ok(depth.depth >= 16); assert.equal(depth.enabled, true);
await evaluate("document.querySelector('[data-farm-game]').scrollIntoView({block:'start',behavior:'instant'})");
await captureScreenshot("farm-overview");
await clickElement("[data-farm-apply]");
await waitFor("document.querySelector('[data-farm-game]').dataset.playing === 'true'", "a role compiled through real DynLex and started");
await waitFor("Number(document.querySelector('[data-farm-stock=logs]').textContent) >= 2", "lumberjack chopping a tree and returning its logs", 120000);
await clickElement("[data-farm-play]");
assert.match(await evaluate("document.querySelector('[data-farm-workers]').textContent"), /Ada · Lumberjack/);
assert.equal(await evaluate("document.querySelector('[data-farm-diagnostics]').hidden"), true);
await clickElement("[data-farm-view=selected]");
await evaluate("new Promise(resolve=>setTimeout(resolve,800));");
await evaluate("document.querySelector('.farm-scene').scrollIntoView({block:'center',behavior:'instant'})");
await captureScreenshot("farm-worker-closeup");
await clickElement("[data-farm-worker=player]");
assert.equal(await evaluate("document.querySelector('[data-farm-role-panel]').hidden"), true, "The farmer cannot be programmed");
assert.equal(await evaluate("document.querySelector('[data-farm-manual]').hidden"), false);
await clickElement("[data-farm-go-barn]");
await waitFor("document.querySelector('[data-farm-person-status]').textContent === 'Arrived.'", "manual farmer movement while workers are paused");
await clickElement("[data-farm-grab=hoe]");
assert.match(await evaluate("document.querySelector('[data-farm-hands]').textContent"), /Hoe/);
await clickElement("[data-farm-grab=seeds]");
await clickElement("[data-farm-grab=axe]");
assert.doesNotMatch(await evaluate("document.querySelector('[data-farm-hands]').textContent"), /Axe/, "Two hands are enforced in the UI");
await clickElement("[data-farm-worker=worker-1]");
await evaluate("document.querySelector('[data-farm-role-name]').value='Harvester'");
await clickElement("[data-farm-add-role]");
assert.equal(await evaluate("editorFor('[data-farm-editor]').getValue()"), "");
assert.equal(await evaluate("document.querySelector('[data-farm-apply]').disabled"), true);
assert.equal(await evaluate("document.querySelector('[data-farm-code-state]').textContent"), "WRITE YOUR CODE");
await captureScreenshot("farm-write-your-role");
await evaluate(`(() => {
  const source=editorFor('[data-farm-editor]');
  source.executeEdits('test',[{range:source.getModel().getFullModelRange(),text:${JSON.stringify("loop forever:\n    walk to the nearest ripe crop\n    harvest the crops\n    walk to the barn\n    store everything")}}]);

  const pace=document.querySelector('[data-farm-speed]');pace.value='2';pace.dispatchEvent(new Event('change'));
})()`);
await clickElement("[data-farm-apply]");
await waitFor("Number(document.querySelector('[data-farm-stock=carrots]').textContent) >= 4", "a player-written role harvesting the first order", 120000);
await clickElement("[data-farm-play]");
await clickElement("[data-farm-deliver]");
assert.equal(await evaluate("document.querySelectorAll('[data-farm-worker]').length"), 3, "The first order unlocks Bo");
assert.match(await evaluate("document.querySelector('[data-farm-order-reward]').textContent"), /cow/i);
await evaluate("document.querySelector('[data-farm-role]').value='lumberjack';document.querySelector('[data-farm-role]').dispatchEvent(new Event('change'))");
await clickElement("[data-farm-apply]");
await waitFor("document.querySelector('[data-farm-workers]').textContent.includes('Ada · Lumberjack')", "reassigning the example role");
await clickElement("[data-farm-play]");
await clickElement("[data-farm-worker=worker-2]");
await clickElement("[data-farm-apply]");
await waitFor("document.querySelector('[data-farm-workers]').textContent.includes('Bo · Lumberjack')", "assigning a second worker to the same role");
await clickElement("[data-farm-play]");
await evaluate(`(() => {
  const source=editorFor('[data-farm-editor]');
  source.executeEdits('test',[{range:source.getModel().getFullModelRange(),text:${JSON.stringify("loop forever:\n    turn right\n    wait")}}]);

})()`);
await clickElement("[data-farm-apply]");
await waitFor("document.querySelector('[data-farm-code-state]').textContent.includes('2 WORKERS USING')", "applying shared role edits");
await clickElement("[data-farm-step]");
const boStatus = await evaluate("document.querySelector('[data-farm-person-status]').textContent");
await clickElement("[data-farm-worker=worker-1]");
assert.equal(await evaluate("document.querySelector('[data-farm-person-status]').textContent"), boStatus);
assert.match(boStatus, /Turning|Waiting/);
await clickElement("[data-farm-worker=worker-2]");
await evaluate("document.querySelector('[data-farm-role-name]').value='Seed courier'");
await clickElement("[data-farm-add-role]");
await evaluate(`(() => {
  const source=editorFor('[data-farm-editor]');
  source.executeEdits('test',[{range:source.getModel().getFullModelRange(),text:${JSON.stringify("to take a breath:\n    wait\n\nloop forever:\n    take a breath")}}]);

})()`);
await clickElement("[data-farm-apply]");
await waitFor("document.querySelector('[data-farm-workers]').textContent.includes('Bo · Seed courier')", "a custom role with a reusable DynLex function");
await clickElement("[data-farm-play]");
await evaluate(`(() => {const source=editorFor('[data-farm-editor]');source.executeEdits('test',[{range:source.getModel().getFullModelRange(),text:'pick up a cloud'}]);})()`);
await clickElement("[data-farm-apply]");
await waitFor("document.querySelector('[data-farm-diagnostics]').hidden === false", "role compiler diagnostics");
assert.match(await evaluate("document.querySelector('[data-farm-diagnostics]').textContent"), /Line 1:/);
await clickElement("[data-farm-reset]");
assert.equal(await evaluate("document.querySelector('[data-farm-game]').dataset.playing"), "false");
assert.equal(await evaluate("document.querySelectorAll('[data-farm-worker]').length"), 2);
assert.deepEqual(await evaluate("Array.from(document.querySelector('[data-farm-role]').options, option=>option.text)"), ["Lumberjack"]);
assert.equal(await evaluate("document.querySelector('[data-farm-stock=logs]').textContent"), "0");
await clickElement("[data-farm-worker=player]");
await evaluate("document.querySelector('.farm-scene').scrollIntoView({block:'center',behavior:'instant'});document.querySelector('[data-farm-board] canvas').focus()");
const playerMarkerX = () => evaluate("document.querySelector('[data-farm-marker=player]').getBoundingClientRect().x");
const beforeWalk = await playerMarkerX();
await command("Input.dispatchKeyEvent", { type: "keyDown", key: "ArrowRight", code: "ArrowRight", windowsVirtualKeyCode: 39 });
await evaluate("new Promise(resolve=>setTimeout(resolve,1200))");
await command("Input.dispatchKeyEvent", { type: "keyUp", key: "ArrowRight", code: "ArrowRight", windowsVirtualKeyCode: 39 });
await evaluate("new Promise(resolve=>setTimeout(resolve,900))");
const afterWalk = await playerMarkerX();
assert.ok(afterWalk - beforeWalk > 15, "Holding a movement key walks the farmer along the path");
await evaluate("new Promise(resolve=>setTimeout(resolve,650))");
assert.ok(Math.abs(await playerMarkerX() - afterWalk) < .2, "Releasing the key stops the farmer");
await clickElement("[data-farm-view=farm]");
await command("Emulation.setDeviceMetricsOverride", { width:390,height:844,deviceScaleFactor:1,mobile:true });
await evaluate("document.querySelector('.farm-scene').scrollIntoView({block:'center',behavior:'instant'});new Promise(resolve=>setTimeout(resolve,900))");
assert.equal(await evaluate("document.documentElement.scrollWidth <= innerWidth"), true);
await captureScreenshot("farm-phone");
assert.deepEqual(runtimeExceptions, []);
console.log("3D farm, real DynLex roles, shared and custom role edits, lumberjacking, manual farmer, held movement keys, inventory, diagnostics, reset and mobile layout passed.");
await closeBrowserSession();
