import assert from "node:assert/strict";
import { navigate, waitFor, evaluate, clickElement, captureScreenshot, runtimeExceptions, consoleErrors, closeBrowserSession } from "./browser_test_driver.mjs";
import { editCode, readCode } from "./editor_test_driver.mjs";
await navigate("/");
await waitFor("document.querySelectorAll('[data-snippet-source][data-language-ready=true]').length===5", "site ready");
await clickElement("[data-farm-challenge-load]");
await waitFor("document.querySelector('[data-river-challenge-mount]').dataset.challengeLoaded==='farm'", "farm ready");
const snapshot = "JSON.parse(localStorage.getItem('dynlex.games.guest')).games.farm.data";
const roleOptions = "[...document.querySelector('[data-farm-role]').options].map(option => ({name:option.text,disabled:option.disabled}))";
const original = await readCode("[data-farm-editor]");
await clickElement("[data-farm-copy-role]");
assert.equal(await readCode("[data-farm-editor]"), original);
assert.equal(await evaluate("document.querySelector('[data-farm-role]').selectedOptions[0].text"), "Lumberjack copy");
await editCode("[data-farm-editor]", "loop forever:\n    walk to the barn\n    wait");
await clickElement("[data-farm-apply]");
await waitFor("document.querySelector('[data-farm-game]').dataset.playing==='true'", "copied role applies");
await clickElement("[data-farm-pause-worker]");
const worker = await evaluate(`${snapshot}.world.workers[0]`);
assert.equal(worker.paused, true);
await clickElement("[data-farm-step]");
assert.deepEqual((await evaluate(`${snapshot}.world.workers[0]`)).routine, worker.routine);
await evaluate("document.querySelector('[data-farm-worker-name]').value='Maple'");
await clickElement("[data-farm-rename-worker]");
assert.equal(await evaluate("document.querySelector('[data-farm-marker=worker-1]').textContent"), "Maple");
assert.equal(await evaluate(`${snapshot}.world.workers[0].name`), "Maple");
await clickElement("[data-farm-delete-role]");
assert.deepEqual(await evaluate(roleOptions), [{name:"Lumberjack",disabled:false}]);
assert.equal(await evaluate(`${snapshot}.world.workers[0].role`), null);
assert.equal(await readCode("[data-farm-editor]"), original);
await clickElement("[data-farm-delete-role]");
assert.equal(await evaluate(`${snapshot}.roles.length`), 0);
assert.deepEqual(await evaluate(roleOptions), []);
assert.equal(await evaluate("document.querySelector('[data-farm-apply]').disabled"), true);
await evaluate("document.querySelector('[data-farm-role-name]').value='Fresh start'");
await clickElement("[data-farm-add-role]");
await editCode("[data-farm-editor]", "turn left");
assert.equal(await evaluate(`${snapshot}.roles[0].source`), "turn left");
await captureScreenshot("farm-role-management");
await navigate("/");
await waitFor("document.querySelectorAll('[data-snippet-source][data-language-ready=true]').length===5", "site reload");
await clickElement("[data-farm-challenge-load]");
await waitFor("document.querySelector('[data-river-challenge-mount]').dataset.challengeLoaded==='farm'", "farm restores");
assert.equal(await evaluate("document.querySelector('[data-farm-worker-name]').value"), "Maple");
assert.equal(await evaluate("document.querySelector('[data-farm-pause-worker]').textContent"), "RESUME WORKER");
assert.equal(await readCode("[data-farm-editor]"), "turn left");
assert.deepEqual(await evaluate(roleOptions), [{name:"Fresh start",disabled:false}]);
assert.deepEqual(runtimeExceptions, []); assert.deepEqual(consoleErrors, []);
console.log("Role copying, deleting the last role, creation, worker names, individual pause, and reload pass.");
await closeBrowserSession();
