import { RIVER_GOALS, newGoalProgress } from "../../web/coding-goals.js";
import assert from "node:assert/strict";
import { SAVE_VERSION, createProgressStore, mergeProgress, readProgress } from "../../web/game-progress.js";
import { createFarm } from "../../web/farm-world.js";
import { createRoles } from "../../web/farm-roles.js";
const memory = new Map();
const storage = {get length(){return memory.size;},key:index=>[...memory.keys()][index],getItem:key=>memory.get(key)??null,setItem:(key,value)=>memory.set(key,value)};
const store = createProgressStore(storage);
const world=createFarm(),roles=createRoles();
world.tick=31;world.player.inventory=[{kind:'bucket',count:1,water:3}];
roles.push({id:'custom-1',name:'Keeper',source:'walk to the nearest chicken',applied:'',program:null,generation:0});
store.save('farm',{world,roles,selected:'player',roleId:'custom-1',speed:2});
store.save('river',{source:'take the sheep',solved:false,coding:newGoalProgress(RIVER_GOALS)});
const restored=createProgressStore(storage);
assert.deepEqual(restored.load('farm'),{world,roles,selected:'player',roleId:'custom-1',speed:2});
assert.equal(restored.load('river').source,'take the sheep');
restored.load('farm').world.tick=0;
assert.equal(restored.load('farm').world.tick,31,'Reading a snapshot does not mutate the stored game');
const guest=store.snapshot;
store.switchProfile('user:alice');assert.equal(store.load('farm'),null);
store.replace(guest);store.save('river',{source:'cross the river',solved:true,coding:newGoalProgress(RIVER_GOALS)});
store.switchProfile('user:bob');assert.equal(store.load('farm'),null);
store.switchProfile('user:alice');assert.equal(store.load('river').solved,true);
store.switchProfile('guest');assert.equal(store.load('river').solved,false,'Profiles cannot overwrite each other');
const remote=structuredClone(guest);remote.games.farm.updatedAt+=1000;remote.games.farm.data.world.tick=80;
const merged=mergeProgress(guest,remote);
assert.equal(merged.games.farm.data.world.tick,80);assert.deepEqual(merged.games.river,guest.games.river);
assert.throws(()=>readProgress('{"version":999}'),/Unsupported/);
let error=null;
const broken=createProgressStore({getItem:()=>null,setItem:()=>{throw new Error('quota');}},e=>error=e);
broken.save('river',{source:'wait'});assert.equal(error.message,'quota');assert.equal(broken.load('river'),null);
assert.throws(()=>broken.replace(guest),/quota/,'A failed account import must abort before syncing back to the cloud');
let writes=0;
const corrupt=createProgressStore({getItem:key=>key.endsWith('profile')?'guest':'{broken',setItem:()=>writes++},e=>error=e);
corrupt.save('river',{source:'wait'});assert.equal(writes,0,'A damaged save is preserved for recovery');
console.log('Both games restore, profiles remain separate, newer saves merge and storage errors are reported.');

const old=structuredClone(guest);old.version=1;
for(const chicken of old.games.farm.data.world.chickens) delete chicken.held;
for(const actor of [old.games.farm.data.world.player,...old.games.farm.data.world.workers]) delete actor.paused;
for(const key of ["dynlex.games.guest","dynlex.games.user:alice","dynlex.games.backup:alice"]) memory.set(key,JSON.stringify(old));
createProgressStore(storage);
for(const key of ["dynlex.games.guest","dynlex.games.user:alice","dynlex.games.backup:alice"]) {
 const data=JSON.parse(memory.get(key));assert.equal(data.version,SAVE_VERSION);assert.equal(data.games.farm.data.world.chickens[0].held,false);
 assert.equal(data.games.farm.data.world.workers[0].paused,false);
 assert.deepEqual(data.games.farm.data.world.areas,[]);
 assert.equal(data.games.farm.data.world.coding.eggs.count,0);
 assert.equal(data.games.river.data.coding.rescue.count,0);
}
assert.equal(readProgress(JSON.stringify(old)).games.farm.data.world.chickens[0].held,false,"Cloud saves migrate at the same boundary");
