import { installEditorAccess } from "./editor_test_driver.mjs";
import assert from "node:assert/strict";
import { navigate, waitFor, evaluate, clickElement, command, captureScreenshot, closeBrowserSession, runtimeExceptions } from "./browser_test_driver.mjs";
async function reload() {
 const origin=await evaluate('performance.timeOrigin');
 await command('Page.reload');
 await waitFor(`performance.timeOrigin!==${origin} && document.readyState==='complete' && document.querySelectorAll('[data-snippet-source][data-language-ready=true]').length===5`,'new page initialized');
}
await navigate('/');
await installEditorAccess();
await waitFor("document.querySelector('[data-live-shader-banner]').dataset.shaderPlaylistReady==='true'",'compiler');
await clickElement('[data-river-challenge-load]');
await waitFor("document.querySelector('[data-river-challenge-mount]').dataset.challengeLoaded==='true'",'river editor');
const river='take the sheep\ncross the river\nput down the sheep';
await evaluate(`(()=>{const source=editorFor('[data-river-editor-shell]');source.executeEdits('test',[{range:source.getModel().getFullModelRange(),text:${JSON.stringify(river)}}]);})()`);
assert.equal(await evaluate("JSON.parse(localStorage.getItem('dynlex.games.guest')).games.river.data.source"),river);
await reload();
await waitFor("document.querySelector('[data-game-resume]')?.hidden===false",'saved river continue button');
await clickElement('[data-game-resume]');
await waitFor("document.querySelector('[data-river-challenge-mount]').dataset.challengeLoaded==='true'",'restored river editor');
assert.equal(await evaluate("editorFor('[data-river-editor-shell]').getValue()"),river);
await clickElement('[data-farm-challenge-load]');
await waitFor("document.querySelector('[data-river-challenge-mount]').dataset.challengeLoaded==='farm'",'farm');
await evaluate(`document.querySelector('[data-farm-role-name]').value='Egg collector'`);
await clickElement('[data-farm-add-role]');
const role='loop forever:\n    walk to the nearest egg\n    collect eggs\n    walk to the nearest chicken\n    wait';
await evaluate(`(()=>{const source=editorFor('[data-farm-editor]');source.executeEdits('test',[{range:source.getModel().getFullModelRange(),text:${JSON.stringify(role)}}]);})()`);
await clickElement('[data-farm-apply]');
await waitFor("document.querySelector('[data-farm-game]').dataset.playing==='true'",'new egg/chicken commands compile and run');
await clickElement('[data-farm-play]');
await clickElement('[data-farm-step]');
await evaluate(`(()=>{const speed=document.querySelector('[data-farm-speed]');speed.value='2';speed.dispatchEvent(new Event('change'));})()`);
await clickElement('[data-farm-select-player]');
await clickElement('[data-farm-go-barn]');
await waitFor("document.querySelector('[data-farm-person-status]').textContent==='Arrived.'",'farmer beside barn');
await clickElement('[data-farm-grab=axe]');
await evaluate("document.querySelector('[data-farm-flag-color]').value='purple'");
await clickElement('[data-farm-add-flag]');
await clickElement('[data-remove-flag=green]');
const before=await evaluate("JSON.parse(localStorage.getItem('dynlex.games.guest')).games.farm.data");
assert.equal(before.world.player.inventory[0].kind,'axe');
assert.ok(before.roles[1].program.length>0);
await reload();
await waitFor("document.querySelector('[data-game-resume]')?.hidden===false",'saved farm continue button');
await clickElement('[data-game-resume]');
await waitFor("document.querySelector('[data-river-challenge-mount]').dataset.challengeLoaded==='farm'",'restored farm');
const after=await evaluate("JSON.parse(localStorage.getItem('dynlex.games.guest')).games.farm.data");
assert.deepEqual(after,before,'The complete farm survives a reload, including code, program position and inventory');
assert.equal(await evaluate("editorFor('[data-farm-editor]').getValue()"),role);
assert.equal(await evaluate("document.querySelector('[data-farm-speed]').value"),'2');
assert.match(await evaluate("document.querySelector('[data-farm-hands]').textContent"),/Axe/);
assert.equal(await evaluate("document.querySelector('[data-farm-game]').dataset.playing"),'false');
await captureScreenshot('farm-restored-progress');
await clickElement('[data-farm-reset]');
await reload();
await waitFor("document.querySelector('[data-game-resume]')?.hidden===false",'reset save');
await clickElement('[data-game-resume]');
await waitFor("document.querySelector('[data-river-challenge-mount]').dataset.challengeLoaded==='farm'",'reset farm restored');
assert.equal(await evaluate("document.querySelector('[data-farm-tick]').textContent"),'TURN 0');
assert.equal(await evaluate("document.querySelector('[data-farm-role]').options.length"),1);
assert.equal(await evaluate("JSON.parse(localStorage.getItem('dynlex.games.guest')).games.river.data.source"),river);
assert.deepEqual(runtimeExceptions,[]);
console.log('River drafts, complete farm state, new animal commands, paused resume and persisted reset passed in Chrome.');
await closeBrowserSession();
