import assert from "node:assert/strict";
import { navigate, waitFor, evaluate, clickElement, command, dispatchKey, captureScreenshot, runtimeExceptions, consoleErrors, closeBrowserSession } from "./browser_test_driver.mjs";
import { withEditor, editCode, readCode } from "./editor_test_driver.mjs";
await navigate('/');
await waitFor("document.querySelectorAll('[data-snippet-source][data-language-ready=true]').length===5", 'all homepage editors connected');
assert.equal(await evaluate("document.querySelectorAll('.snippet-editor-shell, .farm-source-highlight, .river-source-highlight').length"),0);
await clickElement('[data-farm-challenge-load]');
await waitFor("document.querySelector('[data-river-challenge-mount]').dataset.challengeLoaded==='farm'", 'farm ready');
const farm='[data-farm-editor]';
await evaluate("document.querySelector('[data-farm-role-panel]').scrollIntoView({block:'center',behavior:'instant'})");
await editCode(farm,'loop forever:\n    walk to the barn\n    wait');
await waitFor("[...document.querySelectorAll('[data-farm-editor] .view-line:first-child span')].some(s=>getComputedStyle(s).color==='rgb(255, 215, 135)')",'farm semantic colors');
await withEditor(farm,"editor.focus();editor.setPosition({lineNumber:3,column:9});");
await evaluate(`(() => {
  window.highlightSamples=[]; window.sampleHighlight=true;
  function sample(){
    const line=document.querySelector('[data-farm-editor] .view-line');
    highlightSamples.push([...line.querySelectorAll('span')].map(s=>getComputedStyle(s).color).join('|'));
    if(sampleHighlight) requestAnimationFrame(sample);
  }sample();
})()`);
for(const text of [' ','#',' ','h','e','l','l','o']) await command('Input.insertText',{text});
await evaluate('new Promise(resolve=>setTimeout(resolve,900))');
await evaluate('window.sampleHighlight=false');
const samples=await evaluate('highlightSamples');
assert.ok(samples.length>3);
assert.equal(new Set(samples).size,1,'Unedited highlighted lines retain their colors throughout typing: '+JSON.stringify([...new Set(samples)]));
await editCode(farm,'collec');
await withEditor(farm,"editor.focus();editor.setPosition({lineNumber:1,column:model.getLineMaxColumn(1)});");
await command('Input.insertText',{text:'t'});
await waitFor("[...document.querySelectorAll('.suggest-widget.visible .monaco-list-row')].some(row=>row.textContent.includes('collect '))",'collect completion');
await dispatchKey('Tab','Tab',9);
assert.equal(await readCode(farm),'collect ');
await waitFor("[...document.querySelectorAll('.suggest-widget.visible .monaco-list-row')].some(row=>row.textContent.includes('an axe'))",'next completions reopen after Tab without another keystroke');
await command('Input.insertText',{text:'eg'});
await waitFor("document.querySelector('.suggest-widget.visible .monaco-list-row.focused')?.textContent.startsWith('eggfunction')",'egg kind completion selected');
await dispatchKey('ArrowDown','ArrowDown',40);
await waitFor("document.querySelector('.suggest-widget.visible .monaco-list-row.focused')?.textContent.includes('eggs')",'egg completion selected');
await dispatchKey('Tab','Tab',9);
assert.equal(await readCode(farm),'collect eggs');
await dispatchKey('Escape','Escape',27);
await editCode(farm,'walk to the nearest c');
await withEditor(farm,"editor.focus();editor.setPosition({lineNumber:1,column:model.getLineMaxColumn(1)});");
await command('Input.insertText',{text:'h'});
await waitFor("[...document.querySelectorAll('.suggest-widget.visible .monaco-list-row')].some(row=>row.textContent.includes('chicken'))",'nearest chicken completion');
await dispatchKey('Tab','Tab',9);
assert.match(await readCode(farm),/walk to the nearest chicken/);
await captureScreenshot('farm-shared-editor');
await evaluate("document.querySelector('[data-farm-flag-color]').value='purple'");
await clickElement('[data-farm-add-flag]');
assert.equal(await evaluate("document.querySelectorAll('[data-remove-flag=purple]').length"),1);
assert.equal(await evaluate("[...document.querySelector('[data-farm-flag-color]').options].some(o=>o.value==='purple')"),false);
await editCode(farm,'walk to the purple flag');
await clickElement('[data-farm-apply]');
await waitFor("document.querySelector('[data-farm-game]').dataset.playing==='true'",'new flag destination compiles and starts');
await clickElement('[data-farm-play]');
await clickElement('[data-remove-flag=purple]');
assert.equal(await evaluate("document.querySelectorAll('[data-remove-flag=purple]').length"),0);
assert.equal(await evaluate("[...document.querySelector('[data-farm-flag-color]').options].some(o=>o.value==='purple')"),true);
assert.deepEqual(runtimeExceptions,[]);
assert.deepEqual(consoleErrors,[]);
console.log('Shared editors load, highlighting persists during typing, Tab chains collect/item suggestions and accepts chicken completion, and flag controls add/remove unique colors.');
await closeBrowserSession();
