function return value:
    replacement:
        @intrinsic("return", value)

function set variable to value:
    replacement:
        @intrinsic("store", variable, value)

function [a|] pointer to pointee:
    replacement:
        @intrinsic("add pointer depth", pointee)

function nothing:
    replacement:
        @intrinsic("type", "void")

class:
    patterns:
        [a|] cell
    members:
        value

class:
    patterns:
        [an|] owner
    members:
        cell as a pointer to a cell

class:
    patterns:
        [a|] holder
    members:
        owner as a pointer to an owner

function the value in {a holder:container}:
    execute:
        set owned to container's owner
        set selected to owned's cell
        return selected's value

set sample to @intrinsic("construct", a cell, 41)
set pointer to @intrinsic("address of", sample)
set object to @intrinsic("construct", an owner, pointer)
set reference to @intrinsic("address of", object)
set container to @intrinsic("construct", a holder, reference)
set answer to @intrinsic("add", the value in container, 1)
@intrinsic("call", "libc", "exit", nothing, @intrinsic("subtract", answer, 42))
