macro function return value:
	replacement:
		@intrinsic("return", value)

macro function set var to val:
    replacement:
        @intrinsic("store", var, val)

macro function [an|a|] integer:
    replacement:
        @intrinsic("type", "int", 32)

macro function value as [a|an|] bits bit integer:
    replacement:
        @intrinsic("cast", value, @intrinsic("type", "int", bits))

function print msg as line:
    execute:
        @intrinsic("call", "libc", "printf", an integer, "%ld\n", msg as a 64 bit integer)

function left < right:
	execute:
		return @intrinsic("less than", left, right)

macro function left + right:
    replacement:
        @intrinsic("add", left, right)

macro section loop while condition:
	replacement:
		@intrinsic("loop while", condition)

set index to 0

loop while index < 10:
	print index as line
	set index to index + 1