macro effect return value:
	replacement:
		@intrinsic("return", value)

macro effect set var to val:
    replacement:
        @intrinsic("store", var, val)

macro expression value as [a|an|] bits bit integer:
    replacement:
        @intrinsic("cast", value, "integer", bits)

effect print msg as line:
    execute:
        @intrinsic("call", "libc", "printf", "i32", "%ld\n", msg as a 64 bit integer)

expression left < right:
	get:
		return @intrinsic("less than", left, right)

macro expression left + right:
    replacement:
        @intrinsic("add", left, right)

macro section loop while condition:
	replacement:
		@intrinsic("loop while", condition)

set index to 0

loop while index < 10:
	print index as line
	set index to index + 1