function ignore value:
    replacement:
        @intrinsic("discard", value)

function return value:
    replacement:
        @intrinsic("return", value)

function set variable to value:
    replacement:
        @intrinsic("store", variable, value)

function [an|] integer:
    replacement:
        @intrinsic("type", "int")

function fixed quantity:
    replacement:
        @intrinsic("fix", quantity)

function [an|] array of {fixed integer:length} items:
    replacement:
        @intrinsic("array", length)

class:
    patterns:
        [a|] box with {fixed integer:length} items
    members:
        values as an array of length items

function a box with {fixed integer:length} items initialized from value:
    replacement:
        @intrinsic("construct", a box with length items, value)

function the selected box with {fixed integer:length} items:
    execute:
        return a box with length items initialized from [1, 2]

set result to the selected box with 2 items
ignore result
