function return value:
    replacement:
        @intrinsic("return", value)

function set variable to value:
    replacement:
        @intrinsic("store", variable, value)

function left[ |]+[ |]right:
    execute:
        return @intrinsic("add", left, right)

function left[ |]-[ |]right:
    execute:
        return @intrinsic("subtract", left, right)

function left[ |]*[ |]right:
    execute:
        return @intrinsic("multiply", left, right)

function first second suffix:
    execute:
        return @intrinsic("add", first, second)

set red to (red * 0.5 + 0.5 set green to green * 0.5 +import0.5)
