function ignore value:
    replacement:
        @intrinsic("discard", value)

function return value:
    replacement:
        @intrinsic("return", value)

function left - right:
    execute:
        return @intrinsic("subtract", left, right)

flex section if condition:
    replacement:
        @intrinsic("if", condition)

function number has even parity under inversion:
    execute:
        if @intrinsic("not equal", number, 0):
            return number - 1 has odd parity under inversion
        return 1

function number has odd parity under inversion:
    execute:
        if @intrinsic("not equal", number, 0):
            return number - 1 has even parity under inversion
        return 0

ignore 4 has even parity under inversion
