function return value:
    replacement:
        @intrinsic("return", value)

function discard value:
    replacement:
        @intrinsic("discard", value)

function set variable to value:
    replacement:
        @intrinsic("store", variable, value)

function integer:
    replacement:
        @intrinsic("type", "int")

function float:
    replacement:
        @intrinsic("type", "float")

function left - right:
    execute:
        return @intrinsic("cast", @intrinsic("subtract", left, right), @intrinsic("type", "float"))

function {float:value} odded:
    execute:
        return value

function {integer:value} odded:
    globals:
        rollback_guard
    execute:
        set rejected_pointer to @intrinsic("address of", rollback_guard)
        return @intrinsic("cast", value, @intrinsic("type", "float"))

function test value:
    execute:
        return value - 1 odded

function identity value:
    execute:
        return value

set rollback_guard to 32
set safe_target to 0
discard test 4
set safe_pointer to identity @intrinsic("address of", safe_target)
@intrinsic("store at", safe_pointer, 1)
discard @intrinsic("call", "libc", "abs", @intrinsic("type", "int", rollback_guard), 1)
