function return value:
    replacement:
        @intrinsic("return", value)

function ignore value:
    replacement:
        @intrinsic("discard", value)

function set variable to value:
    replacement:
        @intrinsic("store", variable, value)

function [an|] integer:
    replacement:
        @intrinsic("type", "int")

function [a|] floating-point number:
    replacement:
        @intrinsic("type", "float")

function left - right:
    execute:
        return @intrinsic("cast", @intrinsic("subtract", left, right), @intrinsic("type", "float"))

function {floating-point number:value} odded:
    execute:
        return value

function {integer:value} odded:
    globals:
        guard
    execute:
        set rejected to @intrinsic("address of", guard)
        return @intrinsic("cast", value, @intrinsic("type", "float"))

function value tested:
    execute:
        return value - 1 odded

function the identity of value:
    execute:
        return value

set guard to 32
set target to 0
ignore 4 tested
set pointer to the identity of @intrinsic("address of", target)
@intrinsic("store at", pointer, 1)
ignore @intrinsic("call", "libc", "abs", @intrinsic("type", "int", guard), 1)
