import lib/std.dl

class:
    patterns:
        a number box
    members:
        payload as integer

implicitly convert {integer:first}:
    replacement:
        @intrinsic("construct", a number box, first)

implicitly convert {integer:second}:
    replacement:
        @intrinsic("construct", a number box, second)

function unwrap {a number box:boxed}:
    execute:
        return the payload of boxed

print unwrap 8 as line
