function ignore value:
    replacement:
        @intrinsic("discard", value)

function return value:
    replacement:
        @intrinsic("return", value)

function set variable to value:
    replacement:
        @intrinsic("store", variable, value)

function [an|] integer:
    replacement:
        @intrinsic("type", "int")

function fixed quantity:
    replacement:
        @intrinsic("fix", quantity)

function left is right:
    replacement:
        @intrinsic("equal", left, right)

function left and right:
    replacement:
        @intrinsic("and", left, right)

flex section if condition:
    replacement:
        @intrinsic("if", condition)

function the selection for {fixed integer:height} rows and {fixed integer:width} columns:
    execute:
        if height is 4 and width is 4:
            return 7

set result to the selection for 4 rows and 4 columns
ignore @intrinsic("variadic call", "libc", "printf", an integer, 1, "%d\n", result)
