#!/usr/bin/env python3

import argparse
import pathlib
import shutil
import subprocess
import tempfile


SHADERS = (
	("color.vert", "dynlex_graphics_color_vertex"),
	("color.frag", "dynlex_graphics_color_fragment"),
	("texture.vert", "dynlex_graphics_texture_vertex"),
	("texture.frag", "dynlex_graphics_texture_fragment"),
)


def format_header(binaries: list[tuple[str, bytes]]) -> str:
	lines = [
		"#ifndef DYNLEX_GRAPHICS_BUILTIN_SHADERS_H",
		"#define DYNLEX_GRAPHICS_BUILTIN_SHADERS_H",
		"",
		"#include <stdint.h>",
		"",
		"// Generated by: python3 src/runtime/shaders/generate_builtin_shaders.py",
		"// The .spvasm files are authoritative; do not edit this file.",
		"",
	]
	for symbol, data in binaries:
		lines.append(f"_Alignas(uint32_t) static const unsigned char {symbol}[] = {{")
		for offset in range(0, len(data), 20):
			chunk = ", ".join(f"0x{byte:02x}" for byte in data[offset : offset + 20])
			lines.append(f"\t{chunk},")
		lines.extend(
			(
				"};",
				f"static const unsigned int {symbol}_length = {len(data)};",
				"",
			)
		)
	lines.extend(("#endif", ""))
	return "\n".join(lines)


def main() -> int:
	parser = argparse.ArgumentParser(description="Assemble and embed DynLex's built-in Vulkan shaders.")
	parser.add_argument("--check", action="store_true", help="fail if the generated header differs")
	parser.add_argument("--spirv-as", default=shutil.which("spirv-as"), help="path to spirv-as")
	arguments = parser.parse_args()
	if arguments.spirv_as is None:
		parser.error("spirv-as was not found; install the SPIR-V Tools package")

	shader_directory = pathlib.Path(__file__).resolve().parent
	header_path = shader_directory.parent / "graphicsBuiltinShaders.h"
	assembled: list[tuple[str, bytes]] = []
	with tempfile.TemporaryDirectory(prefix="dynlex-shaders-") as temporary_directory:
		for basename, symbol in SHADERS:
			source_path = shader_directory / f"{basename}.spvasm"
			temporary_path = pathlib.Path(temporary_directory) / f"{basename}.spv"
			subprocess.run(
				[arguments.spirv_as, "--target-env", "vulkan1.1", str(source_path), "-o", str(temporary_path)],
				check=True,
			)
			assembled.append((symbol, temporary_path.read_bytes()))

	header = format_header(assembled)
	if arguments.check:
		if not header_path.is_file() or header_path.read_text(encoding="utf-8") != header:
			parser.error(f"generated shader header is outdated: {header_path}")
		return 0

	header_path.write_text(header, encoding="utf-8")
	return 0


if __name__ == "__main__":
	raise SystemExit(main())
