function return value:
    replacement:
        @intrinsic("return", value)

function ignore value:
    replacement:
        @intrinsic("discard", value)

function [an|] integer:
    replacement:
        @intrinsic("type", "int")

function [a|] {fixed integer:bits} bit integer:
    replacement:
        @intrinsic("type", "int", bits)

function [a|] {fixed integer:bits} bit float:
    replacement:
        @intrinsic("type", "float", bits)

function [a|] type:
    replacement:
        @intrinsic("type", "type")

function [a|] constraint:
    replacement:
        @intrinsic("type", "constraint")

function any:
    replacement:
        @intrinsic("type", "any")

function fixed:
    replacement:
        @intrinsic("fix", any)

function fixed value:
    replacement:
        @intrinsic("fix", value)

function [a|] {fixed integer:bits} bit any:
    replacement:
        @intrinsic("type", "any", bits)

function [a|] pointer to pointed:
    replacement:
        @intrinsic("add pointer depth", pointed)

function [an|] array containing {fixed integer:size} element [item|items]:
    replacement:
        @intrinsic("array", size, element)

function value as {fixed type:destination}:
    replacement:
        @intrinsic("cast", value, destination)

function the captured value of {fixed:value}:
    execute:
        return 1

function the description of {a 64 bit any:value}:
    execute:
        return 64

function the description of pointer {a pointer to any:value}:
    execute:
        return 8

function the description of pair {an array containing 2 any items:value}:
    execute:
        return 2

function print value:
    execute:
        ignore @intrinsic("variadic call", "libc", "printf", an integer, 1, "%d\n", value)

print the captured value of 12
print the captured value of an integer
print the description of (1 as a 64 bit integer)
print the description of (1 as a 64 bit float)
print the description of pointer "value"
print the description of pair [1, 2]
