# DynLex Array Library

import lib/std.dl

local function the allocation of count bytes:
    execute:
        return @intrinsic("call", "libc", "calloc", a pointer to a byte, count as a word sized integer, 1 as a word sized integer)

local function the allocation of count bytes as {type:kind}:
    replacement:
        @intrinsic("call", "libc", "calloc", kind, count as a word sized integer, 1 as a word sized integer)

flex function allocate count bytes:
    replacement:
        set the subject to the allocation of count bytes
flex function allocate count bytes as {type:kind}:
    replacement:
        set the subject to the allocation of count bytes as kind
local function:
    patterns:
        the allocation of count slots of {type:kind}
    execute:
        return the allocation of (count * the size of kind) bytes as a pointer to kind

local function:
    patterns:
        the allocation of one slot of {type:kind}
    execute:
        return the allocation of the size of kind bytes as a pointer to kind

to get {type:kind} array of {integer:count} slots:
    return the allocation of count slots of kind

flex function:
    patterns:
        allocate count slots of {type:kind}
    replacement:
        set the subject to the allocation of count slots of kind

flex function:
    patterns:
        allocate one slot of {type:kind}
    replacement:
        set the subject to the allocation of one slot of kind

local function the allocation of count slots initialized with value:
    execute:
        set array to the allocation of count slots of the type of value
        set index to 0
        loop while index < count:
            initialize value at (array + index)
            increment index
        return array

local function the allocation of one slot initialized with value:
    execute:
        set array to the allocation of one slot of the type of value
        initialize value at array
        return array

to get storage for {integer:count} slots initialized with value:
    return the allocation of count slots initialized with value

to get storage for one slot initialized with value:
    return the allocation of one slot initialized with value

flex function allocate count slots of value:
    replacement:
        set the subject to the allocation of count slots initialized with value
flex function allocate one slot of value:
    replacement:
        set the subject to the allocation of one slot initialized with value
to store value into array at index:
    @intrinsic("store at", array + index, value)
