# DynLex Array Library

import lib/std.dl

function allocate count bytes:
    execute:
        return @intrinsic("call", "libc", "calloc", a pointer to a byte, count as a word sized integer, 1 as a word sized integer)

function allocate count bytes as output_type:
    replacement:
        @intrinsic("call", "libc", "calloc", output_type, count as a word sized integer, 1 as a word sized integer)

function allocate count items:
    replacement:
        allocate count bytes

function:
    patterns:
        allocate count slots of {type:elementtype}
    execute:
        return allocate (count * the size of elementtype) bytes as a pointer to elementtype

function allocate count slots of value:
    execute:
        set array to allocate count slots of the type of value
        set i to 0
        loop while i < count:
            store value into array at i
            set i to i + 1
        return array

function store value into array at index:
    execute:
        @intrinsic("store at", array + index, value)

function item index of array:
    execute:
        return @intrinsic("dereference", array + index)
