import lib/std.dl

function atomically load {a pointer to a value:address}:
    replacement:
        @intrinsic("atomic load", address, "seq_cst")

function atomically load relaxed {a pointer to a value:address}:
    replacement:
        @intrinsic("atomic load", address, "relaxed")

function atomically load acquire {a pointer to a value:address}:
    replacement:
        @intrinsic("atomic load", address, "acquire")

function atomically store {a value:value} at {a pointer to a value:address}:
    replacement:
        @intrinsic("atomic store", address, value, "seq_cst")

function atomically store relaxed {a value:value} at {a pointer to a value:address}:
    replacement:
        @intrinsic("atomic store", address, value, "relaxed")

function atomically store release {a value:value} at {a pointer to a value:address}:
    replacement:
        @intrinsic("atomic store", address, value, "release")

function atomically exchange {a value:value} at {a pointer to a value:address}:
    replacement:
        @intrinsic("atomic exchange", address, value, "seq_cst")

function atomically add {a value:value} at {a pointer to a value:address}:
    replacement:
        @intrinsic("atomic fetch add", address, value, "seq_cst")

function atomically add acquire release {a value:value} at {a pointer to a value:address}:
    replacement:
        @intrinsic("atomic fetch add", address, value, "acq_rel")

function atomically subtract {a value:value} at {a pointer to a value:address}:
    replacement:
        @intrinsic("atomic fetch sub", address, value, "seq_cst")
