# DynLex Map Library

import lib/list.dl

class:
    patterns:
        [a|] map
    members:
        keys
        values

function an empty map from {type:domain} to {type:range}:
    execute:
        set keys to an empty list of domain
        set values to an empty list of range
        set initial to @intrinsic("construct", a map, keys, values)
        allocate 1 slots of initial and set result to it
        return result

function the number of entries in {a pointer to a map:mapping}:
    execute:
        return the length of the keys of mapping

function the index of key in {a pointer to a map:mapping}:
    execute:
        set cursor to 0
        loop while cursor < the length of the keys of mapping:
            if the item at cursor in the keys of mapping = key:
                return cursor
            set cursor to (cursor + 1)
        return 0 - 1

function {a pointer to a map:mapping} contains key {any:key}:
    execute:
        return the index of key in mapping >= 0

function the value for key in {a pointer to a map:mapping}:
    execute:
        set position to the index of key in mapping
        if position < 0:
            @intrinsic("call", "libc", "abort", nothing)
        return the item at position in the values of mapping

function put value for key in {a pointer to a map:mapping}:
    execute:
        set position to the index of key in mapping
        if position >= 0:
            store value into the data of the values of mapping at position
        else:
            append key to the keys of mapping
            append value to the values of mapping

function remove key from {a pointer to a map:mapping}:
    execute:
        set position to the index of key in mapping
        if position >= 0:
            remove item position from the keys of mapping
            remove item position from the values of mapping

function clear {a pointer to a map:mapping}:
    execute:
        clear the keys of mapping
        clear the values of mapping

function free {a pointer to a map:mapping}:
    execute:
        free (the keys of mapping)
        free (the values of mapping)
        @intrinsic("call", "libc", "free", nothing, mapping)
