import lib/std.dl

class:
	patterns:
		[a|] CPU {fixed integer:rows} by {fixed integer:columns} matrix
	members:
		values as an array of rows * columns items

function a GPU {fixed integer:rows} by {fixed integer:columns} matrix:
	replacement:
		@intrinsic("matrix", rows, columns)

function a {fixed integer:rows} by {fixed integer:columns} matrix:
	replacement:
		a GPU rows by columns matrix if the build target is GPU, else a CPU rows by columns matrix

function a new {fixed integer:rows} by {fixed integer:columns} matrix from value:
	replacement:
		@intrinsic("construct", a rows by columns matrix, value)

function an identity {fixed integer:rows} by {fixed integer:columns} matrix:
	execute:
		if rows is 4 and columns is 4:
			return a new rows by columns matrix from [
				1.0, 0.0, 0.0, 0.0, 
				0.0, 1.0, 0.0, 0.0, 
				0.0, 0.0, 1.0, 0.0, 
				0.0, 0.0, 0.0, 1.0
			]
		else if rows is 3 and columns is 3:
			return a new rows by columns matrix from [
				1.0, 0.0, 0.0, 
				0.0, 1.0, 0.0, 
				0.0, 0.0, 1.0
			]
		else if rows is 2 and columns is 2:
			return a new rows by columns matrix from [
				1.0, 0.0, 
				0.0, 1.0
			]
