# DynLex Set Library

import lib/list.dl

class:
    patterns:
        [a|] unique set
    members:
        values

function an empty set of {type:kind}:
    execute:
        set values to an empty list of kind
        set initial to @intrinsic("construct", a unique set, values)
        allocate 1 slots of initial and set result to it
        return result

function the size of {a pointer to a unique set:items}:
    execute:
        return the length of the values of items

function {a pointer to a unique set:items} contains value:
    execute:
        return the values of items contains value

function {a pointer to a unique set:items} does not contain value:
    execute:
        return the inverse of (the values of items contains value)

function add value to {a pointer to a unique set:items}:
    execute:
        if items does not contain value:
            append value to the values of items

function remove value from {a pointer to a unique set:items}:
    execute:
        set position to the index of value in the values of items
        if position >= 0:
            remove item position from the values of items

function clear {a pointer to a unique set:items}:
    execute:
        clear the values of items

function free {a pointer to a unique set:items}:
    execute:
        free (the values of items)
        @intrinsic("call", "libc", "free", nothing, items)
