import lib/std.dl

# Fragment shader I/O

the fragment coordinates means: @intrinsic("shader input", "FragCoord")
the fragment x coordinate means: the element at 0 in @intrinsic("shader input", "FragCoord")
the fragment y coordinate means: the element at 1 in @intrinsic("shader input", "FragCoord")
function set the fragment color with a red channel of {a value:red}, a green channel of {a value:green}, a blue channel of {a value:blue} and an alpha channel of {a value:alpha}:
    replacement:
        @intrinsic(
            "shader output",
            @intrinsic("construct", an aggregate of 4 floating-point number values, red, green, blue, alpha)
        )

# Vertex shader I/O

the vertex position means: @intrinsic("shader input", "Position")
the vertex x means: the element at 0 in @intrinsic("shader input", "Position")
the vertex y means: the element at 1 in @intrinsic("shader input", "Position")
the vertex z means: the element at 2 in @intrinsic("shader input", "Position")
the vertex w means: the element at 3 in @intrinsic("shader input", "Position")
function set the output position with x {a value:horizontal}, y {a value:vertical}, z {a value:depth} and w {a value:magnitude}:
    replacement:
        @intrinsic(
            "shader output",
            @intrinsic("construct", an aggregate of 4 floating-point number values, horizontal, vertical, depth, magnitude)
        )

# Vertex-to-fragment interpolants

function set [the|] shader interpolant named {a value:name} with an x coordinate of {a value:horizontal}, a y coordinate of {a value:vertical}, a z coordinate of {a value:depth} and a w coordinate of {a value:magnitude}:
    replacement:
        @intrinsic("shader interpolant output", name, horizontal, vertical, depth, magnitude)
[the|] shader interpolant x named name means: the element at 0 in @intrinsic("shader interpolant input", name)
[the|] shader interpolant y named name means: the element at 1 in @intrinsic("shader interpolant input", name)
[the|] shader interpolant z named name means: the element at 2 in @intrinsic("shader interpolant input", name)
[the|] shader interpolant w named name means: the element at 3 in @intrinsic("shader interpolant input", name)
# Shader uniforms (values passed from host each frame)

the shader time means: @intrinsic("shader uniform", "time", 0)
the shader render pass means: @intrinsic("shader uniform", "render_pass", 1)
