import lib/std.dl

# Fragment shader I/O

macro function [the|] fragment coordinates:
    replacement:
        @intrinsic("shader input", "FragCoord")

macro function [the|] fragment x coordinate:
    replacement:
        @intrinsic("extract element", @intrinsic("shader input", "FragCoord"), 0)

macro function [the|] fragment y coordinate:
    replacement:
        @intrinsic("extract element", @intrinsic("shader input", "FragCoord"), 1)

macro function set [the|] fragment color to r g b a:
    replacement:
        @intrinsic("shader output", r, g, b, a)

# Vertex shader I/O

macro function [the|] vertex position:
    replacement:
        @intrinsic("shader input", "Position")

macro function [the|] vertex x:
    replacement:
        @intrinsic("extract element", @intrinsic("shader input", "Position"), 0)

macro function [the|] vertex y:
    replacement:
        @intrinsic("extract element", @intrinsic("shader input", "Position"), 1)

macro function [the|] vertex z:
    replacement:
        @intrinsic("extract element", @intrinsic("shader input", "Position"), 2)

macro function [the|] vertex w:
    replacement:
        @intrinsic("extract element", @intrinsic("shader input", "Position"), 3)

macro function set [the|] output position to x y z w:
    replacement:
        @intrinsic("shader output", x, y, z, w)

# Shader uniforms (values passed from host each frame)

macro function [the|] shader time:
    replacement:
        @intrinsic("shader uniform", "time")
