import std.dl

class:
    patterns:
        vector
    members:
        x, y, z

function a new vector with x vx, y vy and z vz:
    execute:
        set result to @intrinsic("construct", vector)
        set the x of result to vx
        set the y of result to vy
        set the z of result to vz
        return result

function add value to {vector:target}:
    execute:
        add value to the x of target
        add value to the y of target
        add value to the z of target

function multiply {vector:value} by factor:
    execute:
        multiply the x of value by factor
        multiply the y of value by factor
        multiply the z of value by factor

function print {vector:msg}:
    execute:
        @intrinsic("call", "libc", "printf", an integer, "[%g, %g, %g]\n", the x of msg as a float, the y of msg as a float, the z of msg as a float)
