import lib/std.dl

flex section forward body:
    replacement:
        execute the body
        discard missing_direct_tail

flex function relay body:
    replacement:
        execute the body

flex section forward nested body:
    replacement:
        relay body
        discard missing_nested_tail

function result for condition:
    execute:
        if condition:
            forward body:
                loop while true:
                    discard 0
        if condition:
            forward body:
                loop while true:
                    discard 0
        if condition:
            forward nested body:
                loop while true:
                    discard 0
        return 7

print result for @intrinsic("equal", @intrinsic("call", "libc", "abs", an integer, 0), 1) as line
