import lib/geometry.dl

set location to @intrinsic(
    "construct",
    a point,
    @intrinsic("construct", an aggregate of 3 float values, 1.0, 2.0, 3.0)
)
set pigment to @intrinsic(
    "construct",
    a color,
    @intrinsic("construct", an aggregate of 4 float values, 0.1, 0.2, 0.3, 1.0)
)

increase the x coordinate of location by 4.0
decrease the y coordinate of location by 1.0
set the blue channel of pigment to 0.8

print location's x as a line
print location's y as a line
print location's z as a line
print pigment's red as a line
print pigment's blue as a line
