function ignore value:
    replacement:
        @intrinsic("discard", value)

section if condition:
    replacement:
        @intrinsic("if", condition)

function the first recursive result for value:
    execute:
        if @intrinsic("greater than", value, 0):
            @intrinsic("return", the second recursive result for @intrinsic("subtract", value, 1))
        @intrinsic("return", @intrinsic("equal", 1, 2))

function the second recursive result for value:
    execute:
        if @intrinsic("greater than", value, 0):
            @intrinsic("return", the first recursive result for @intrinsic("subtract", value, 1))
        @intrinsic("return", @intrinsic("equal", 1, 2))

ignore (the first recursive result for 2)
