function return value:
    replacement:
        @intrinsic("return", value)

function ignore value:
    replacement:
        @intrinsic("discard", value)

function set variable to value:
    replacement:
        @intrinsic("store", variable, value)

function left + right:
    replacement:
        @intrinsic("add", left, right)

function the sum of left and right:
    execute:
        set total to left
        set total to (total + right)
        return total

ignore @intrinsic("type", "int", the sum of 4 and 4)
