[package]
name = "dynlex-wgsl-translator"
version = "0.1.0"
edition = "2021"
rust-version = "1.87"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
naga = { version = "=30.0.1", default-features = false, features = ["spv-in", "wgsl-out"] }

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = true

