function set variable to value:
    replacement:
        @intrinsic("store", variable, value)

function return value:
    replacement:
        @intrinsic("return", value)

function left = right:
    replacement:
        @intrinsic("equal", left, right)

function not value:
    replacement:
        @intrinsic("not", value)

flex section if condition:
    replacement:
        @intrinsic("if", condition)

function left + right:
    replacement:
        @intrinsic("add", left, right)

class:
    patterns:
        [a|] list
    members:
        capacity

class:
    patterns:
        [a|] wrapper
    members:
        values

flex function ensure {list:values} using sample:
    replacement:
        set new_capacity to the capacity of values + sample

flex function append item to {list:values}:
    replacement:
        ensure values using item

function {list:values} contains item:
    execute:
        return the capacity of values = item

function {wrapper:items} contains item:
    execute:
        return the values of items contains item

flex function add item to {wrapper:items}:
    replacement:
        if not items contains item:
            set updated_values to the values of items
            append item to updated_values
            set the values of items to updated_values

set values to @intrinsic("construct", a list, 7)
set items to @intrinsic("construct", a wrapper, values)
add 1 to items
