import lib/random.dl
import lib/array.dl

function fill plan levels jump_ms slide_ms with count count using seed seed_value:
	execute:
		seed random with seed_value
		set i to 0
		set current_level to 0
		loop while i < count:
			set next_jump_ms to 420 + a random number mod 180
			set next_slide_ms to 100 + a random number mod 180
			if i mod 4 = 0:
				set next_jump_ms to 340 + a random number mod 120
			if i mod 3 = 0 and current_level < 4:
				set current_level to current_level + 1
			else if i mod 5 = 0 and current_level > 0:
				set current_level to current_level - 1
			store current_level into levels at i
			store next_jump_ms into jump_ms at i
			store next_slide_ms into slide_ms at i
			set i to i + 1
