import lib/random.dl
import lib/array.dl

class:
	patterns:
		[a|] route step
	members:
		level as an integer
		jump duration as an integer
		slide duration as an integer

class:
	patterns:
		[a|] route plan
	members:
		count, steps

a route step at level {integer:level} with jump duration {integer:jump} and slide duration {integer:slide} means: @intrinsic("construct", a route step, level, jump, slide)

to get a route plan with {integer:count} steps:
	set storage to a route step array of count slots
	return @intrinsic("construct", a route plan, count, storage)

to fill {route plan:plan} using seed {integer:seed}:
	seed the random number generator with seed
	set index to 0
	set level to 0
	loop while index < plan's count:
		set jump to (420 + the remainder of (a random number) divided by 180)
		set slide to (100 + the remainder of (a random number) divided by 180)
		if the remainder of index divided by 4 = 0:
			set jump to (340 + the remainder of (a random number) divided by 120)
		if the remainder of index divided by 3 = 0 and level < 4:
			increment level
		else if the remainder of index divided by 5 = 0 and level > 0:
			decrement level
		store (a route step at level level with jump duration jump and slide duration slide) into plan's steps at index
		increment index
