function return value:
    replacement:
        @intrinsic("return", value)

function ignore value:
    replacement:
        @intrinsic("discard", value)

function left + right:
    execute:
        return @intrinsic("add", left, right)

function left * right:
    execute:
        return @intrinsic("multiply", left, right)

function one more than value:
    execute:
        return value + 1

function value doubled:
    execute:
        return value * one more than value

ignore @intrinsic("array", 5 doubled)
