import std.dl

function [a known value|a known value]:
    replacement:
        1

function [the selection of {word:left} using alpha|the selection of {word:right} using beta]:
    execute:
        return 1

function [the recurrence of|the recurrence of] argument after marker:
    replacement:
        argument
        the recurrence of marker after marker

print (the selection of one using alpha) as a line
print (the selection of two using beta) as a line
