import std.dl

function [a known value|a known value]:
    replacement:
        1

function [the selection of {integer:left} using alpha|the selection of {integer:right} using beta]:
    execute:
        return 1

function [the recurrence of|the recurrence of] argument after marker:
    replacement:
        @intrinsic("discard", argument)
        the recurrence of marker after marker

print (the selection of 1 using alpha) as a line
print (the selection of 2 using beta) as a line
