function ignore value:
    replacement:
        @intrinsic("discard", value)

function set variable to value:
    replacement:
        @intrinsic("store", variable, value)

function [an|] integer:
    replacement:
        @intrinsic("type", "int")

function [a|] C string:
    replacement:
        @intrinsic("type", "string")

function the length of {C string:value}:
    execute:
        return 99

function return value:
    replacement:
        @intrinsic("return", value)

class:
    patterns:
        point
    members:
        x as an integer
        y as an integer

class:
    patterns:
        content
    members:
        length as an integer

class:
    patterns:
        record
    members:
        data as a C string

set location to @intrinsic("construct", point, 10, 20)
set location's x to 12
set the x of location to 13
set reference to @intrinsic("address of", location)
set the x of reference to 14
set paragraph to @intrinsic("construct", content, 7)
set length to the length of paragraph
set object to @intrinsic("construct", record, "hello")
set nested to the length of the data of object
set points to @intrinsic("construct", point, 20, 30)
set points' x to 21

ignore @intrinsic("variadic call", "libc", "printf", an integer, 1, "%d\n", the x of location)
ignore @intrinsic("variadic call", "libc", "printf", an integer, 1, "%d\n", the x of reference)
ignore @intrinsic("variadic call", "libc", "printf", an integer, 1, "%d\n", length)
ignore @intrinsic("variadic call", "libc", "printf", an integer, 1, "%d\n", nested)
ignore @intrinsic("variadic call", "libc", "printf", an integer, 1, "%d\n", points' x)
