function return value:
	replacement:
		@intrinsic("return", value)

function set variable to value:
	replacement:
		@intrinsic("store", variable, value)

function [a|] C string:
	replacement:
		@intrinsic("type", "string")

function left[ |]+[ |]right:
	execute:
		return @intrinsic("add", left, right)

function {C string:left}[ |]+[ |]{C string:right}:
	execute:
		return left

function add value to target:
	replacement:
		set target to target + value

function apply gravity to velocity:
	execute:
		add 1.15 to velocity

@intrinsic("store", velocity, 0.0)
apply gravity to velocity
apply gravity to velocity
apply gravity to velocity
