function [an|] integer:
    replacement:
        @intrinsic("type", "int")

function floating:
    replacement:
        @intrinsic("type", "float")

function fixed quantity:
    replacement:
        @intrinsic("fix", quantity)

function accept {the wrapped type of 32:value}:
    execute:
        @intrinsic("discard", value)

function the wrapped type of value:
    replacement:
        the type of value

function the type of {fixed floating:value}:
    replacement:
        @intrinsic("discard", value)
        @intrinsic("type", "float", 32)

function the type of {fixed integer:value}:
    replacement:
        @intrinsic("discard", value)
        @intrinsic("type", "int", 32)

accept 1
