function ignore value:
    replacement:
        @intrinsic("discard", value)

function return value:
    replacement:
        @intrinsic("return", value)

function [a|] boolean:
    replacement:
        @intrinsic("type", "bool")

function true:
    replacement:
        @intrinsic("cast", 1, a boolean)

function false:
    replacement:
        @intrinsic("cast", 0, a boolean)

function [a|] pointer to pointee:
    replacement:
        @intrinsic("add pointer depth", pointee)

function value as destination:
    replacement:
        @intrinsic("cast", value, destination)

flex section if condition:
    replacement:
        @intrinsic("if", condition)

class:
    patterns:
        [a|] cell
    members:
        value

class:
    patterns:
        [an|] owner
    members:
        cell as a pointer to a cell

class:
    patterns:
        [an|] outcome
    members:
        owner as a pointer to an owner

class:
    patterns:
        [an|] envelope
    members:
        outcome

function a concrete outcome containing {a pointer to an owner:owned}:
    replacement:
        @intrinsic("construct", an outcome, owned)

function an empty outcome:
    replacement:
        @intrinsic("construct", an outcome, 0 as a pointer to an owner)

function a concrete envelope containing {a pointer to an owner:owned}:
    replacement:
        @intrinsic("construct", an envelope, a concrete outcome containing owned)

function an empty envelope:
    replacement:
        @intrinsic("construct", an envelope, an empty outcome)

function the outcome for {a pointer to an owner:owned} when {boolean:condition}:
    execute:
        if condition:
            return a concrete outcome containing owned
        return an empty outcome

function the reversed outcome for {a pointer to an owner:owned} when {boolean:condition}:
    execute:
        if condition:
            return an empty outcome
        return a concrete outcome containing owned

function the selected outcome for {a pointer to an owner:owned} when {boolean:condition}:
    replacement:
        @intrinsic("select", condition, a concrete outcome containing owned, an empty outcome)

function the reversed selected outcome for {a pointer to an owner:owned} when {boolean:condition}:
    replacement:
        @intrinsic("select", condition, an empty outcome, a concrete outcome containing owned)

function the envelope for {a pointer to an owner:owned} when {boolean:condition}:
    execute:
        if condition:
            return an empty envelope
        return a concrete envelope containing owned

function the selected outcome array for {a pointer to an owner:owned} when {boolean:condition}:
    replacement:
        @intrinsic("select", condition, [an empty outcome], [a concrete outcome containing owned])

@intrinsic("store", value, @intrinsic("construct", a cell, 41))
@intrinsic("store", pointer, @intrinsic("address of", value))
@intrinsic("store", object, @intrinsic("construct", an owner, pointer))
@intrinsic("store", reference, @intrinsic("address of", object))
ignore the outcome for reference when true
ignore the outcome for reference when false
ignore the reversed outcome for reference when true
ignore the reversed outcome for reference when false
ignore the selected outcome for reference when true
ignore the selected outcome for reference when false
ignore the reversed selected outcome for reference when true
ignore the reversed selected outcome for reference when false
ignore the envelope for reference when true
ignore the envelope for reference when false
ignore the selected outcome array for reference when true
ignore the selected outcome array for reference when false
