flex section if condition:
	replacement:
		@intrinsic("if", condition)

function first value:
	execute:
		if @intrinsic("not equal", value, 0):
			@intrinsic("store", recursive_result, second @intrinsic("subtract", value, 1))
			@intrinsic("return", recursive_result)
		@intrinsic("return", @intrinsic("equal", value, 0))

function second value:
	execute:
		if @intrinsic("not equal", value, 0):
			@intrinsic("store", recursive_result, first @intrinsic("subtract", value, 1))
			@intrinsic("return", recursive_result)
		@intrinsic("return", @intrinsic("equal", value, 0))

@intrinsic("discard", first 2)
