import lib/std.dl

function recursive:
	execute:
		@intrinsic("discard", recursive)
		@intrinsic("return", 1)

function referenced direct recursive {integer:value}:
	execute:
		if value > 0:
			return referenced direct recursive (value - 1)
		return value

function referenced mutual first {integer:value}:
	execute:
		if value > 0:
			return referenced mutual second (value - 1)
		return value

function referenced mutual second {integer:value}:
	execute:
		if value > 0:
			return referenced mutual first (value - 1)
		return value

ignore @intrinsic("function", "recursive")
set direct to the function named "referenced direct recursive $"
set mutual to the function named "referenced mutual first $"

ignore direct
ignore mutual
