function integer:
    replacement:
        @intrinsic("type", "int")
function the length of values:
    replacement:
        @intrinsic("type extent", values, 0)
function left < right:
    execute:
        @intrinsic("return", @intrinsic("less than", left, right))
flex function loop while condition:
    replacement:
        @intrinsic("loop while", condition)
flex section [loop |]while condition:
    replacement:
        loop while condition
flex section loop index from start to end:
    replacement:
        @intrinsic("store", index, start)
        loop while index < end:
            @intrinsic("execute body")
            @intrinsic("store", index, @intrinsic("add", index, 1))
function examine item:
    execute:
        loop index from 0 to the length of item:
            @intrinsic("discard", @intrinsic("call", "libc", "putchar", integer, 88))
        @intrinsic("return", 55)
@intrinsic("store", sample, [1, 2])
@intrinsic("discard", @intrinsic("call", "libc", "putchar", integer, examine sample))
