function fixed tofix:
	replacement:
		@intrinsic("fix", tofix)

function [een|] integer:
	replacement:
		@intrinsic("type", "int")

function [een|] {fixed integer:bits} bit integer:
	replacement:
		@intrinsic("type", "int", bits)

function waarde als {fixed integer:bits} bit integer:
	replacement:
		@intrinsic("cast", waarde, @intrinsic("type", "int", bits))

function discard waarde:
	replacement:
		@intrinsic("discard", waarde)

function zeg bericht:
	execute:
		discard @intrinsic("variadic call", "libc", "printf", een 32 bit integer, 1, "%s\n", bericht)

function toon getal:
	execute:
		discard @intrinsic("variadic call", "libc", "printf", een 32 bit integer, 1, "%ld\n", getal als 64 bit integer)

function maak variabele waarde:
	replacement:
		@intrinsic("store", variabele, waarde)

zeg "hallo"
maak a 10
zeg "a is:"
toon a
