import { readFile, writeFile } from "node:fs/promises";
const root = new URL("../", import.meta.url);
const manifest = JSON.parse(await readFile(new URL("src/web/ide/dist/.vite/manifest.json", root), "utf8"));
const styles = new Set();
function visit(key) {
  const entry = manifest[key];
  for (const css of entry.css ?? []) styles.add(css);
  for (const dependency of entry.imports ?? []) visit(dependency);
}
visit("src/editor.js");
await writeFile(new URL("web/editor.js", root), `// Generated by scripts/copy_web_editor.mjs from the shared IDE build.\n${[...styles].map(css => `{
  const link = document.createElement("link");
  link.rel = "stylesheet";
  link.href = new URL(${JSON.stringify("./"+css)}, import.meta.url).href;
  document.head.append(link);
}`).join("\n")}\nexport * from ${JSON.stringify("./"+manifest["src/editor.js"].file)};\n`);
