import {writeFile} from "node:fs/promises";
import {ITEMS,DESTINATIONS,ACTIONS,CONDITIONS,DIRECTIONS,FEATURES,ROLE_NAMES,ITEM_ALIASES,TARGET_ALIASES,SUBJECT_TARGET,SUBJECT_ITEMS,NO_TARGET,targetId} from "../web/farm-vocabulary.js";

const number=value=>`@intrinsic("cast", ${value<0?`@intrinsic("negate", ${-value})`:value}, a farm number)`;
const construct=(type,...values)=>`@intrinsic("construct", farm ${type}, ${values.join(", ")})`;
const lines=[`# Generated by scripts/generate_farm_vocabulary.mjs from web/farm-vocabulary.js.
# Values describe live targets and item selections; each worker evaluates its own plan.
import lib/subject.dl

a farm number means: @intrinsic("type", "int", 32)
a farm text means: @intrinsic("type", "string")

to emit farm text:
    @intrinsic("discard", @intrinsic("variadic call", "libc", "printf", a farm number, 1, "%s\\n", text))
`];
for (const [type,members] of Object.entries({
  item:["identifier as a farm number","amount as a farm number"],
  target:["identifier as a farm number","area as a farm text"],
  "entity kind":["identifier as a farm number"],
  direction:["identifier as a farm number"], feature:["identifier as a farm number"], role:["identifier as a farm number"],
  condition:["identifier as a farm number","argument as a farm number","amount as a farm number","target as a farm number","area as a farm text"]
})) lines.push(`class:\n    patterns:\n        farm ${type}\n    members:\n${members.map(member=>`        ${member}`).join("\n")}\n`);
for (const {id,phrase,aliases} of ITEMS) for (const name of [phrase,...aliases]) lines.push(`${name} means: ${construct("item",number(id),number(/^(a|an) /.test(name)?1:-1))}`);
for (const [name,id] of ITEM_ALIASES) lines.push(`${name} means: ${construct("item",number(id),number(name==="my bucket"?1:-1))}`);
lines.push(`{a farm number:count} {farm item:items} means: ${construct("item","items's identifier","count")}`);
for (const {id,literal,kind} of DESTINATIONS) {
  if (literal !== null) lines.push(`${literal} means: ${construct("target",number(id),'""')}`);
  if (kind !== null) lines.push(`${kind} means: ${construct("entity kind",number(id))}`);
}
lines.push(`the nearest {farm entity kind:kind} means: ${construct("target","kind's identifier",'""')}`);
for (const [phrase,key] of TARGET_ALIASES) lines.push(`${phrase} means: ${construct("target",number(targetId(key)),'""')}`);
lines.push(`{farm target:target} in [the|] area {a farm text:name} means: ${construct("target","target's identifier","name")}`);
for (const [type,entries] of [["direction",DIRECTIONS],["feature",FEATURES],["role",ROLE_NAMES]]) {
  entries.forEach((name,id)=>lines.push(`${name} means: ${construct(type,number(id))}`));
}
for (const [op,entries] of [["DO",ACTIONS],["IF",CONDITIONS]]) for (const entry of entries) for (const pattern of entry.patterns) {
  const has=name=>pattern.includes(`:${name}}`);
  const argument=has("items")?"items's identifier":has("direction")?"direction's identifier":has("feature")?"feature's identifier":has("role")?"role's identifier":number(entry.defaults.argument??0);
  const amount=has("count")?"count":has("items")?"items's amount":number(-1);
  const target=has("target")?"target's identifier":number(entry.defaults.target??NO_TARGET);
  const area=has("target")?"target's area":'""';
  const values=[number(entry.id),argument,amount,target,area];
  const emit=`@intrinsic("discard", @intrinsic("variadic call", "libc", "printf", a farm number, 1, "DO|%d|%d|%d|%d|%s\\n", ${values.join(", ")}))`;
  const body=[];
  if (entry.subject) body.push(`@intrinsic("set subject", ${entry.subject==="target"?construct("target",number(SUBJECT_TARGET),'""'):construct("item",number(SUBJECT_ITEMS),number(-1))})`);
  body.push(op==="DO"?emit:construct("condition",...values));
  lines.push(`\nflex function ${pattern}:\n    replacement:\n${body.map(line=>`        ${line}`).join("\n")}`);
}
lines.push(`
flex section if {farm condition:condition}:
    replacement:
        @intrinsic("discard", @intrinsic("variadic call", "libc", "printf", a farm number, 1, "IF|%d|%d|%d|%d|%s\\n", condition's identifier, condition's argument, condition's amount, condition's target, condition's area))
        @intrinsic("execute body")
        emit farm "END"

flex section else:
    replacement:
        emit farm "ELSE"
        @intrinsic("execute body")
        emit farm "END"

flex section else if {farm condition:condition}:
    replacement:
        emit farm "ELSE"
        if condition:
            @intrinsic("execute body")
        emit farm "END"

flex section loop forever:
    replacement:
        emit farm "LOOP|-1"
        @intrinsic("execute body")
        emit farm "END"

flex section loop count [time|times]:
    replacement:
        @intrinsic("discard", @intrinsic("variadic call", "libc", "printf", a farm number, 1, "LOOP|%d\\n", @intrinsic("cast", count, a farm number)))
        @intrinsic("execute body")
        emit farm "END"
`);
await writeFile(new URL("../lib/farm_challenge.dl",import.meta.url),lines.join("\n").trimEnd()+"\n");
