import fs from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { semanticHighlightKey } from "../web/snippet-highlight-key.js";

const projectDir = path.resolve(import.meta.dirname, "..");
const homepagePath = path.join(projectDir, "web/index.html");
const compilerDir = path.join(projectDir, "src/web/ide/public/compiler");
const outputPath = path.join(projectDir, "web/snippet-highlights.js");
const legendOutputPath = path.join(projectDir, "web/semantic-token-legend.js");
const checkOnly = process.argv.slice(2).includes("--check");

function decodeCharacterReferences(value) {
  const namedReferences = new Map([
    ["amp", "&"],
    ["apos", "'"],
    ["gt", ">"],
    ["lt", "<"],
    ["quot", "\""]
  ]);

  return value.replace(/&(#(?:x[0-9a-f]+|\d+)|[a-z]+);/gi, (reference, name) => {
    if (name.startsWith("#")) {
      const hexadecimal = name[1].toLowerCase() === "x";
      const digits = name.slice(hexadecimal ? 2 : 1);
      const codePoint = Number.parseInt(digits, hexadecimal ? 16 : 10);
      if (!Number.isInteger(codePoint) || !Number.isFinite(codePoint)) {
        throw new Error(`Invalid character reference: ${reference}`);
      }
      return String.fromCodePoint(codePoint);
    }

    const decoded = namedReferences.get(name.toLowerCase());
    if (decoded === undefined) {
      throw new Error(`Unsupported character reference: ${reference}`);
    }
    return decoded;
  });
}

function extractSnippetSources(html) {
  const sources = [];
  const textareaPattern = /<textarea\b(?=[^>]*\bdata-snippet-source\b)[^>]*>([\s\S]*?)<\/textarea>/gi;
  for (const match of html.matchAll(textareaPattern)) {
    sources.push(decodeCharacterReferences(match[1]));
  }
  if (sources.length === 0) {
    throw new Error("Homepage contains no editable snippet sources");
  }
  return [...new Set(sources)];
}

function validateSemanticTokens(payload) {
  if (!payload || !Array.isArray(payload.data) || payload.data.length % 5 !== 0) {
    throw new Error("Compiler returned an invalid semantic-token data array");
  }
  if (!payload.legend || !Array.isArray(payload.legend.tokenTypes) || !Array.isArray(payload.legend.tokenModifiers)) {
    throw new Error("Compiler returned an invalid semantic-token legend");
  }
}

function renderLegendModule(legend) {
  return `// Generated by scripts/generate_homepage_highlights.mjs. Do not edit manually.
export const semanticTokenLegend = Object.freeze(${JSON.stringify(legend)});
`;
}

function renderCacheModule(entries) {
  const renderedEntries = entries
    .map(([key, data]) => `  [${JSON.stringify(key)}, Object.freeze(${JSON.stringify(data)})]`)
    .join(",\n");

  return `// Generated by scripts/generate_homepage_highlights.mjs. Do not edit manually.
export { semanticTokenLegend } from "./semantic-token-legend.js";

export const semanticHighlightCache = new Map([
${renderedEntries}
]);
`;
}

const modulePath = path.join(compilerDir, "dynlex_web.js");
const imported = await import(pathToFileURL(modulePath).href);
const createModule = imported.default ?? imported;
if (typeof createModule !== "function") {
  throw new Error(`Expected module factory export from ${modulePath}`);
}

const compiler = await createModule({
  locateFile(fileName) {
    return path.join(compilerDir, fileName);
  }
});
compiler.ccall("dynlex_web_init", null, [], []);

const sources = extractSnippetSources(fs.readFileSync(homepagePath, "utf8"));
const cacheEntries = [];
let semanticTokenLegend = null;

for (const source of sources) {
  compiler.ccall("dynlex_web_set_main_source", null, ["string"], [source]);
  const compileStatus = compiler.ccall("dynlex_web_compile_and_emit_wasm", "number", [], []);
  if (compileStatus !== 0) {
    const diagnostics = compiler.ccall("dynlex_web_get_diagnostics_json", "string", [], []);
    throw new Error(`Homepage example does not compile: ${diagnostics}`);
  }
  const payload = JSON.parse(compiler.ccall("dynlex_web_get_lsp_semantic_tokens_json", "string", [], []));
  validateSemanticTokens(payload);

  if (semanticTokenLegend === null) {
    semanticTokenLegend = payload.legend;
  } else if (JSON.stringify(semanticTokenLegend) !== JSON.stringify(payload.legend)) {
    throw new Error("Compiler returned inconsistent semantic-token legends");
  }
  cacheEntries.push([await semanticHighlightKey(source), payload.data]);
}

const generatedLegendModule = renderLegendModule(semanticTokenLegend);
const generatedCacheModule = renderCacheModule(cacheEntries);
if (checkOnly) {
  const legendIsCurrent = fs.existsSync(legendOutputPath)
    && fs.readFileSync(legendOutputPath, "utf8") === generatedLegendModule;
  const cacheIsCurrent = fs.existsSync(outputPath)
    && fs.readFileSync(outputPath, "utf8") === generatedCacheModule;
  if (!legendIsCurrent || !cacheIsCurrent) {
    throw new Error("Homepage semantic-highlight cache is stale; run scripts/generate_homepage_highlights.mjs");
  }
} else {
  fs.writeFileSync(legendOutputPath, generatedLegendModule);
  fs.writeFileSync(outputPath, generatedCacheModule);
  console.log(`Wrote ${path.relative(projectDir, outputPath)} for ${cacheEntries.length} unique snippets.`);
}
