#!/usr/bin/env python3

import argparse
import pathlib
import shutil
import subprocess
import tempfile
import struct


SHADERS = (
	("color.vert", "dynlex_graphics_color_vertex"),
	("color.frag", "dynlex_graphics_color_fragment"),
	("texture.vert", "dynlex_graphics_texture_vertex"),
	("texture.frag", "dynlex_graphics_texture_fragment"),
)


def format_library(binaries: list[tuple[str, bytes]]) -> str:
    lines = [
        "# Generated by: python3 scripts/generate_builtin_shaders.py",
        "# The lib/shaders/*.spvasm files are authoritative.",
        "import lib/std.dl",
        "",
    ]
    for symbol, data in binaries:
        words = struct.unpack(f"<{len(data) // 4}I", data)
        lines.extend((f"function {symbol}:", "    execute:", "        return ["))
        for offset in range(0, len(words), 8):
            entries = [f"{word} as a 32 bit unsigned integer" for word in words[offset:offset + 8]]
            suffix = "," if offset + 8 < len(words) else ""
            lines.append("            " + ", ".join(entries) + suffix)
        lines.extend(("        ]", ""))
    return "\n".join(lines)


def main() -> int:
	parser = argparse.ArgumentParser(description="Assemble and embed DynLex's built-in Vulkan shaders.")
	parser.add_argument("--check", action="store_true", help="fail if the generated DynLex library differs")
	parser.add_argument("--spirv-as", default=shutil.which("spirv-as"), help="path to spirv-as")
	arguments = parser.parse_args()
	if arguments.spirv_as is None:
		parser.error("spirv-as was not found; install the SPIR-V Tools package")

	shader_directory = pathlib.Path(__file__).resolve().parent.parent / "lib/shaders"
	library_path = shader_directory.parent / "graphics_builtin_shaders.dl"
	assembled: list[tuple[str, bytes]] = []
	with tempfile.TemporaryDirectory(prefix="dynlex-shaders-") as temporary_directory:
		for basename, symbol in SHADERS:
			source_path = shader_directory / f"{basename}.spvasm"
			temporary_path = pathlib.Path(temporary_directory) / f"{basename}.spv"
			subprocess.run(
				[arguments.spirv_as, "--target-env", "vulkan1.1", str(source_path), "-o", str(temporary_path)],
				check=True,
			)
			assembled.append((symbol, temporary_path.read_bytes()))

	library = format_library(assembled)
	if arguments.check:
		if not library_path.is_file() or library_path.read_text(encoding="utf-8") != library:
			parser.error(f"generated shader library is outdated: {library_path}")
		return 0

	library_path.write_text(library, encoding="utf-8")
	return 0


if __name__ == "__main__":
	raise SystemExit(main())
