import { readFile, writeFile } from "node:fs/promises";

const root = new URL("../", import.meta.url);
const colors = JSON.parse(await readFile(new URL("shared/call-colors.json", root), "utf8"));
const check = process.argv.includes("--check");
async function output(path, source) {
  const url = new URL(path, root);
  if (check) {
    if (await readFile(url, "utf8") !== source) throw new Error(`${path} needs scripts/generate_call_colors.mjs`);
  } else await writeFile(url, source);
}

await output("src/cpp/lsp/callDepthColors.h", `// Generated by scripts/generate_call_colors.mjs from shared/call-colors.json.\n#pragma once\n\nnamespace lsp {\ninline constexpr int callDepthColorCount = ${colors.length};\n} // namespace lsp\n`);
const packageUrl = new URL("vscode-extension/package.json", root);
const manifest = JSON.parse(await readFile(packageUrl, "utf8"));
manifest.contributes.semanticTokenModifiers = colors.map((_, depth) => ({
  id: `callDepth${depth}`, description: `Call nesting color ${depth + 1}; colors repeat every ${colors.length} levels.`
}));
const rules = manifest.contributes.configurationDefaults["editor.semanticTokenColorCustomizations"].rules;
for (const selector of Object.keys(rules)) if (selector.includes(".callDepth")) delete rules[selector];
for (const [depth, color] of colors.entries()) {
  for (const type of ["function", "intrinsic", "type"]) rules[`${type}.callDepth${depth}:dynlex`] = { foreground: `#${color.editor}` };
}
await output("vscode-extension/package.json", JSON.stringify(manifest, null, 2) + "\n");
await output("web/call-colors.css", "/* Generated by scripts/generate_call_colors.mjs from shared/call-colors.json. */\n" + colors.map((color, depth) => `.shader-code-token.calldepth${depth} { color: #${color.dark}; }`).join("\n") + "\n");
