import lib/std.dl

set base to 10
set values to [base, base + 5, 30]

print @intrinsic("load at", @intrinsic("address of", values), 0) as line
print @intrinsic("load at", @intrinsic("address of", values), 1) as line
print @intrinsic("load at", @intrinsic("address of", values), 2) as line

set numericValues to [1, 2.5, 3]

print @intrinsic("load at", @intrinsic("address of", numericValues), 0) as line
print @intrinsic("load at", @intrinsic("address of", numericValues), 1) as line
print @intrinsic("load at", @intrinsic("address of", numericValues), 2) as line

set multilineValues to [
    base,
    base + 20,
    @intrinsic("load at", @intrinsic("address of", numericValues), 0) as an integer
]

print @intrinsic("load at", @intrinsic("address of", multilineValues), 0) as line
print @intrinsic("load at", @intrinsic("address of", multilineValues), 1) as line
print @intrinsic("load at", @intrinsic("address of", multilineValues), 2) as line
