import lib/std.dl

set base to 10
set values to [base, base + 5, 30]

print @intrinsic("dereference", @intrinsic("add", @intrinsic("cast", @intrinsic("address of", values), a pointer to integer), 0)) as line
print @intrinsic("dereference", @intrinsic("add", @intrinsic("cast", @intrinsic("address of", values), a pointer to integer), 1)) as line
print @intrinsic("dereference", @intrinsic("add", @intrinsic("cast", @intrinsic("address of", values), a pointer to integer), 2)) as line

set numericValues to [1, 2.5, 3]

print @intrinsic("dereference", @intrinsic("add", @intrinsic("cast", @intrinsic("address of", numericValues), a pointer to float), 0)) as line
print @intrinsic("dereference", @intrinsic("add", @intrinsic("cast", @intrinsic("address of", numericValues), a pointer to float), 1)) as line
print @intrinsic("dereference", @intrinsic("add", @intrinsic("cast", @intrinsic("address of", numericValues), a pointer to float), 2)) as line

set multilineValues to [
    base,
    base + 20,
    @intrinsic("dereference", @intrinsic("cast", @intrinsic("address of", numericValues), a pointer to float)) as an integer
]

print @intrinsic("dereference", @intrinsic("add", @intrinsic("cast", @intrinsic("address of", multilineValues), a pointer to integer), 0)) as line
print @intrinsic("dereference", @intrinsic("add", @intrinsic("cast", @intrinsic("address of", multilineValues), a pointer to integer), 1)) as line
print @intrinsic("dereference", @intrinsic("add", @intrinsic("cast", @intrinsic("address of", multilineValues), a pointer to integer), 2)) as line
