import lib/std.dl

function [the|] text of {integer:value}:
    execute:
        return the string form of value

function {string:text} at character {integer:index}:
    execute:
        return character index of text

function {integer:number} at character {integer:index}:
    execute:
        return number / (10 raised to the power of index) mod 10

print the length of (the text of 123 at character 0) as line
