function ignore value:
    replacement:
        @intrinsic("discard", value)

flex function set variable to value:
    replacement:
        @intrinsic("store", variable, value)

flex section if condition:
    replacement:
        @intrinsic("if", condition)

flex section else if condition:
    replacement:
        @intrinsic("else if", condition)

flex section else:
    replacement:
        @intrinsic("else")

flex function clamp variable between low and high:
    replacement:
        if @intrinsic("less than", variable, low):
            set variable to low
        if @intrinsic("greater than", variable, high):
            set variable to high

flex function print the compile-time selected branch:
    replacement:
        if @intrinsic("equal", 1, 0):
            @intrinsic("discard", @intrinsic("variadic call", "libc", "printf", @intrinsic("type", "int", 32), 1, "%d\n", 1))
        else if @intrinsic("equal", 1, 1):
            @intrinsic("discard", @intrinsic("variadic call", "libc", "printf", @intrinsic("type", "int", 32), 1, "%d\n", 2))
        else:
            @intrinsic("discard", @intrinsic("variadic call", "libc", "printf", @intrinsic("type", "int", 32), 1, "%d\n", 3))

@intrinsic("store", value, 20)
clamp value between 0 and 10
ignore @intrinsic("variadic call", "libc", "printf", @intrinsic("type", "int", 32), 1, "%d\n", value)
print the compile-time selected branch
