function ignore value:
    replacement:
        @intrinsic("discard", value)

function [an|] integer:
    replacement:
        @intrinsic("type", "int")

class:
    patterns:
        [a|] failing lifecycle value
    members:
        marker as an integer
    retain:
        @intrinsic("discard", @intrinsic("address of", 1))
    release:
        @intrinsic("discard", @intrinsic("lifecycle value"))

@intrinsic("store", value, @intrinsic("construct", a failing lifecycle value, 0))
ignore value
