import lib/graphics.dl

print the escape key as a line
print the A key as a line
print the D key as a line
print the E key as a line
print the Q key as a line
print the S key as a line
print the W key as a line
print the 0 key as a line
print the 1 key as a line
print the 9 key as a line
print the right arrow key as a line
print the left arrow key as a line
print the down arrow key as a line
print the up arrow key as a line

if false:
	set window to a new hidden window with width 1 and height 1
	if window != 0 as a pointer to a byte:
		set failed to false
		if key (the W key) is down in window:
			set failed to true
		set released to key (the W key) is up in window
		if released = false:
			set failed to true
		set digit to key (the 1 key) is up in window
		if digit = false:
			set failed to true
		close the window
		if failed:
			return 1
