import lib/std.dl

class:
    patterns:
        [a|] tracked value
    members:
        references as a pointer to an integer
    retain:
        set count to @intrinsic("dereference", the references of @intrinsic("lifecycle value"))
        @intrinsic("store at", the references of @intrinsic("lifecycle value"), count + 1)
    release:
        set count to @intrinsic("dereference", the references of @intrinsic("lifecycle value")) - 1
        @intrinsic("store at", the references of @intrinsic("lifecycle value"), count)

class:
    patterns:
        managed container
    members:
        value as tracked value

set previous to 0
set current to 0
set container to @intrinsic("construct", managed container, @intrinsic("construct", a tracked value, the address of previous))
set address to the address of the value of container
@intrinsic("store at", address, @intrinsic("construct", a tracked value, the address of current))
print previous as a line
print current as a line
