import lib/std.dl
# this effect has a single pattern, defined right at the effect definition line instead of in a pattern section.
expression var's next power of two:
	get:
		set result to 1
		while result < var:
			multiply result by 2
		return result

effect say message:
	execute:
		print message as line

class:
	patterns:
		octet
		unsigned char
		uint_8


expression number%:
	get:
		return number * 0.01

say "Hello, World!"
		
# should print 8
print 5.5's next power of two as line

#should print 0.1
print 10% as line