import lib/std.dl
# this function has a single pattern, defined right at the function definition line instead of in a pattern section.
function variable's next power of two:
	execute:
		set result to 1
		while result < variable:
			multiply result by 2
		return result

function say message:
	execute:
		print message as a line

class:
	patterns:
		[an|] octet
		[an|] unsigned char
		[an|] eight bit unsigned integer


function number%:
	execute:
		return number * 0.01

say "Hello, World!"
		
# should print 8
print 5.5's next power of two as a line

#should print 0.1
print 10% as a line
