import lib/std.dl
# this function has a single pattern, defined right at the function definition line instead of in a pattern section.
function var's next power of two:
	execute:
		set result to 1
		while result < var:
			multiply result by 2
		return result

function say message:
	execute:
		print message as line

class:
	patterns:
		octet
		unsigned char
		uint_8


function number%:
	execute:
		return number * 0.01

say "Hello, World!"
		
# should print 8
print 5.5's next power of two as line

#should print 0.1
print 10% as line