import lib/process.dl

function {process result:result} failed to launch:
    replacement:
        the inverse of (result was launched)

set argument to a new string buffer containing 3 bytes
store 65 as a byte into the data of argument at 0
store 0 as a byte into the data of argument at 1
store 66 as a byte into the data of argument at 2

set command to a process command for "unused-executable"
add argument as an argument to command
launch command and set child to it
set expected to the string form of "Process argument must not be null or contain a zero byte"

print whether child failed to launch as a line
print whether (the starting error of child = expected) as a line

run command and set result to it
print whether result failed to launch as a line
print whether result failed as a line
print whether (result's error message = expected) as a line
