name: Pipeline

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    secrets: inherit

  pages:
    needs: ci
    if: ${{ needs.ci.result == 'success' }}
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: ./.github/workflows/pages.yml
    secrets: inherit
