// Generated by scripts/copy_web_editor.mjs from the shared IDE build.
{
  const link = document.createElement("link");
  link.rel = "stylesheet";
  link.href = new URL("./assets/editor-C3aiza2j.css", import.meta.url).href;
  document.head.append(link);
}
export * from "./assets/editor-pMRELcjP.js";
